import { describe, test, expect } from 'bun:test';
import * as impl04 from '../impls/04-live-intl/index.ts';
import * as impl07 from '../impls/07-baked-rules/index.ts';
import * as impl08 from '../impls/08-verified-sharing/index.ts';
import * as impl10 from '../impls/10-audited-rules/index.ts';
import { genMeta } from '../shared/schedule.ts';
import { formatOffset } from '../shared/fmt.ts';

// value-asserting tests for table-based impls only run when the tables were
// generated by this runtime (see genMeta provenance)
const tablesAligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;

const HOUR_MS = 3_600_000;
const ITERATIONS = 25;

const median = (xs: number[]) => xs.toSorted((a, b) => a - b)[xs.length >> 1]!;

const timeMs = (fn: () => void) => {
  const t0 = Bun.nanoseconds();
  fn();
  return (Bun.nanoseconds() - t0) / 1e6;
};

const variants = [
  { id: '04-live-intl', ...impl04 },
  { id: '07-baked-rules', ...impl07 },
  { id: '08-verified-sharing', ...impl08 },
  { id: '10-audited-rules', ...impl10 },
];

for (const { id, getTimeZonesAt, clearCache } of variants) {
  describe(`${id} hour-bucket cache behavior`, () => {
    test('same hour bucket returns the identical (memoized) array', () => {
      clearCache();

      const ts = Date.UTC(2026, 6, 15, 12, 0);
      const a = getTimeZonesAt(ts);
      const b = getTimeZonesAt(ts + 59 * 60_000); // 59 min later, same bucket

      expect(b).toBe(a);
    });

    test('different hour bucket recomputes', () => {
      clearCache();

      const ts = Date.UTC(2026, 6, 15, 12, 30);
      const a = getTimeZonesAt(ts);
      const b = getTimeZonesAt(ts + HOUR_MS); // next bucket

      expect(b).not.toBe(a);
    });

    test('single slot: returning to a previous bucket recomputes', () => {
      clearCache();

      const ts = Date.UTC(2026, 6, 15, 12, 30);
      const a = getTimeZonesAt(ts);
      getTimeZonesAt(ts + HOUR_MS); // evicts the single slot
      const a2 = getTimeZonesAt(ts); // same bucket as `a`, but recomputed

      expect(a2).not.toBe(a);
      expect(a2).toEqual(a);
    });

    test('mid-hour timestamps evaluate at the bucket start', () => {
      // same bucket queried mid-hour vs at its exact start must deep-equal
      const ts = Date.UTC(2026, 2, 8, 6, 37); // inside the hour before US spring-forward

      clearCache();
      const midHour = getTimeZonesAt(ts);

      clearCache();
      const atStart = getTimeZonesAt(Date.UTC(2026, 2, 8, 6, 0));

      expect(midHour).toEqual(atStart);
    });

    const liveValues =
      id === '04-live-intl' ||
      (id === '08-verified-sharing' && typeof Temporal === 'undefined') ||
      tablesAligned;
    const testValues = liveValues ? test : test.skip;

    testValues('bucket boundaries still resolve DST transitions correctly', () => {
      clearCache();

      // US spring-forward at 2026-03-08 07:00 UTC: adjacent buckets disagree
      const before = getTimeZonesAt(Date.UTC(2026, 2, 8, 6, 59)).find((z) => z.name === 'America/New_York')!;
      const after = getTimeZonesAt(Date.UTC(2026, 2, 8, 7, 1)).find((z) => z.name === 'America/New_York')!;

      expect(`${before.abbr} ${formatOffset(before.offset)}`).toBe('EST -05:00');
      expect(`${after.abbr} ${formatOffset(after.offset)}`).toBe('EDT -04:00');
    });
  });

  describe(`${id} hour-bucket cache performance`, () => {
    // warm the formatter caches so miss timings measure steady-state
    // recompute cost, not one-time Intl.DateTimeFormat construction
    getTimeZonesAt(Date.UTC(2026, 4, 1));

    test('cache-hit loop: timestamps within one hour bucket', () => {
      clearCache();

      const base = Date.UTC(2026, 5, 1, 12, 0);
      getTimeZonesAt(base); // populate the slot

      const times: number[] = [];

      for (let i = 0; i < ITERATIONS; i++) {
        times.push(timeMs(() => getTimeZonesAt(base + i * 1000)));
      }

      const med = median(times);

      console.log(`    [${id}] hit median: ${(med * 1000).toFixed(1)}µs`);

      expect(med).toBeLessThan(0.5); // hits never re-run Intl work
    });

    test('cache-miss loop: each iteration advances to the next hour bucket', () => {
      clearCache();

      const base = Date.UTC(2026, 5, 1, 12, 0);
      const times: number[] = [];
      let prev: unknown;

      for (let i = 0; i < ITERATIONS; i++) {
        let result: unknown;
        times.push(timeMs(() => (result = getTimeZonesAt(base + i * HOUR_MS))));

        expect(result).not.toBe(prev); // every miss recomputed (new array)
        prev = result;
      }

      const med = median(times);

      console.log(`    [${id}] miss median: ${med.toFixed(3)}ms`);

      expect(med).toBeLessThan(50); // recompute, but never formatter reconstruction
    });
  });
}

describe('hour-bucket quantization window (Australia/Lord_Howe)', () => {
  // Lord Howe is the only zone whose transition falls MID-HOUR in UTC: its
  // +10:30 base offset puts the 2026 spring-forward at Oct 3 15:30Z. Since
  // the memo evaluates each bucket at its start, calls in 15:30-16:00Z
  // return the pre-transition value — a KNOWN design tradeoff (bounded at
  // 30 min, for this single zone), pinned here so a future change to the
  // bucketing strategy revisits it deliberately.
  for (const { id, getTimeZonesAt, clearCache } of variants) {
    const liveValues =
      id === '04-live-intl' ||
      (id === '08-verified-sharing' && typeof Temporal === 'undefined') ||
      tablesAligned;
    const testValues = liveValues ? test : test.skip;

    testValues(`${id}: mid-hour transition quantizes to the bucket start`, () => {
      const zone = (ts: number) => {
        clearCache();
        return getTimeZonesAt(ts).find((z) => z.name === 'Australia/Lord_Howe')!;
      };

      // 15:45Z is after the 15:30Z transition, but the bucket evaluates at
      // 15:00Z -> still reports pre-transition LHST +10:30
      const quantized = zone(Date.UTC(2026, 9, 3, 15, 45));
      expect(`${quantized.abbr} ${formatOffset(quantized.offset)}`).toBe('LHST +10:30');

      // the next bucket sees the new offset
      const nextBucket = zone(Date.UTC(2026, 9, 3, 16, 0));
      expect(`${nextBucket.abbr} ${formatOffset(nextBucket.offset)}`).toBe('LHDT +11:00');
    });
  }
});

describe('cache-hit vs cache-miss ratio', () => {
  test('hits are at least 10x faster than misses (all impls)', () => {
    for (const { getTimeZonesAt, clearCache } of variants) {
      clearCache();

      const base = Date.UTC(2026, 8, 1, 12, 0);
      const missTimes: number[] = [];
      const hitTimes: number[] = [];

      for (let i = 0; i < ITERATIONS; i++) {
        missTimes.push(timeMs(() => getTimeZonesAt(base + i * HOUR_MS)));
      }

      getTimeZonesAt(base);

      for (let i = 0; i < ITERATIONS; i++) {
        hitTimes.push(timeMs(() => getTimeZonesAt(base + i * 1000)));
      }

      expect(median(hitTimes)).toBeLessThan(median(missTimes) / 10);
    }
  });
});
