import { describe, test, expect } from 'bun:test';
import { classGroups, genMeta } from '../shared/classes.ts';
import { zones } from '../shared/zones.ts';
import { liveParts } from '../shared/live.ts';

const YEAR = 2026;

// the class table is impl 08's grouping-hint source: members of a group must
// produce identical live-Intl output to their representative all year.
// validation against live Intl is only meaningful when this runtime's ICU
// matches the one the table was generated from (see genMeta provenance);
// Chrome-generated tables are verified in-browser by tools/gen-chrome.ts,
// and impl 08 additionally re-verifies groups at runtime via Temporal.
const aligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
const testIfAligned = aligned ? test : test.skip;

if (!aligned) {
  console.warn(`  [classes.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl validation`);
}

describe('class table (impl 08 grouping hints)', () => {
  testIfAligned('covers only known zones, no zone in two groups', () => {
    const seen = new Set<string>();
    const known = new Set(zones);

    for (const group of classGroups) {
      expect(group.length).toBeGreaterThan(1);

      for (const z of group) {
        expect(known.has(z)).toBe(true);
        expect(seen.has(z)).toBe(false);
        seen.add(z);
      }
    }
  });

  testIfAligned('group members match their representative in live Intl output across the year', () => {
    const instants: number[] = [];

    for (let m = 0; m < 12; m++) {
      for (const d of [1, 15]) instants.push(Date.UTC(YEAR, m, d, 12));
    }

    // 2026 US/EU/AU transition edges
    for (const t of [
      Date.UTC(YEAR, 2, 8, 7),
      Date.UTC(YEAR, 2, 29, 1),
      Date.UTC(YEAR, 3, 4, 16),
      Date.UTC(YEAR, 9, 3, 16),
      Date.UTC(YEAR, 9, 25, 1),
      Date.UTC(YEAR, 10, 1, 6),
    ]) {
      instants.push(t - 60_000, t + 60_000);
    }

    for (const ts of instants) {
      for (const group of classGroups) {
        const rep = liveParts(group[0]!, ts);

        for (let i = 1; i < group.length; i++) {
          const member = liveParts(group[i]!, ts);

          expect(`${group[i]} ${member.abbr} ${member.offset}`).toBe(`${group[i]} ${rep.abbr} ${rep.offset}`);
        }
      }
    }
  });
});
