import { describe, test, expect } from 'bun:test';
import { impls } from '../impls/registry.ts';
import { fixtures } from '../shared/fixtures.ts';
import { zones } from '../shared/zones.ts';
import { fmtCache, tzNameFromFormat, isoOffsetFromLongOffset } from '../shared/fmt.ts';
import { genMeta } from '../shared/schedule.ts';
import { aliasOfZone } from '../shared/zoneLinks.ts';

// impls 06 and 07 depend on generated tables, so they can only be checked
// against this runtime's Intl when the tables were generated by this runtime
// (Chrome-generated tables are verified in-browser by tools/gen-chrome.ts)
const tablesAligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
// 08 ignores the tables when Temporal is unavailable (plain-04 fallback), so
// it stays live-checkable under misaligned tables in such runtimes
const tableIndependent = (id: string) =>
  id === '04-live-intl' || (id === '08-verified-sharing' && typeof Temporal === 'undefined');
const liveCheckedImpls = tablesAligned ? impls : impls.filter((i) => tableIndependent(i.id));

if (liveCheckedImpls.length < impls.length) {
  console.warn(`  [dst.test] tables generated by "${genMeta.host}" != runtime; skipping table-based impls (verified in-browser instead)`);
}

for (const impl of liveCheckedImpls) {
  describe(impl.id, () => {
    for (const f of fixtures) {
      test(`${f.zone} @ ${new Date(f.ts).toISOString()} (${f.desc}) -> ${f.abbr} ${f.offset}`, () => {
        const info = impl.getTimeZonesAt(f.ts).find((z) => z.name === f.zone);

        expect(info).toBeDefined();
        expect(info!.abbr).toBe(f.abbr);
        expect(info!.offset).toBe(f.offset);
      });
    }

    test('no abbr is a raw GMT±HH:MM offset and all offsets are well-formed', () => {
      for (const info of impl.getTimeZonesAt(Date.UTC(2026, 6, 15))) {
        expect(info.abbr).not.toMatch(/^GMT[+-]\d{2}:\d{2}$/);
        expect(info.offset).toMatch(/^[+-]\d{2}:\d{2}$/);
      }
    });
  });
}

describe('aliasOf metadata', () => {
  // aliasOf marks legacy-spelled zone names with their modern canonical id;
  // this runtime's zone list determines which spellings appear
  test('legacy-enumerated zones carry aliasOf, canonical zones never do', () => {
    for (const impl of liveCheckedImpls) {
      for (const info of impl.getTimeZonesAt(Date.UTC(2026, 6, 15))) {
        expect(info.aliasOf).toBe(aliasOfZone.get(info.name));
      }
    }
  });

  test('runtime-specific: Asia/Choibalsan (if enumerated) aliases Asia/Ulaanbaatar', () => {
    if (!zones.includes('Asia/Choibalsan')) return;

    for (const impl of liveCheckedImpls) {
      const info = impl.getTimeZonesAt(Date.UTC(2026, 6, 15)).find((z) => z.name === 'Asia/Choibalsan')!;

      expect(info.aliasOf).toBe('Asia/Ulaanbaatar');
      // the canonical target is co-enumerated here, so a picker would drop
      // the alias entry while keeping its name searchable
      expect(zones.includes('Asia/Ulaanbaatar')).toBe(true);
    }
  });
});

describe('consistency', () => {
  // impls derive offsets arithmetically from wall-clock fields; verify every
  // zone's offset against Intl's own 'longOffset' output as an oracle
  // (this was the offset strategy of an earlier, removed implementation)
  const offsetFmt = fmtCache({ timeZoneName: 'longOffset' });

  test('offsets match the Intl longOffset oracle for all zones (winter + summer)', () => {
    for (const ts of [Date.UTC(2026, 0, 15), Date.UTC(2026, 6, 15)]) {
      const date = new Date(ts);

      for (const impl of liveCheckedImpls) {
        const result = impl.getTimeZonesAt(ts);

        expect(result.length).toBe(zones.length);

        for (const z of result) {
          const expected = isoOffsetFromLongOffset(tzNameFromFormat(offsetFmt(z.name).format(date)));
          expect(`${z.name} ${z.offset}`).toBe(`${z.name} ${expected}`);
        }
      }
    }
  });

  // results must not depend on the host TZ; the runner script also executes
  // the whole suite under several TZ env values (see package.json scripts)
  test(`results are identical regardless of host TZ (currently TZ=${process.env.TZ ?? 'system'})`, () => {
    const ts = Date.UTC(2026, 2, 8, 7, 1); // 1 min after US spring-forward

    for (const impl of liveCheckedImpls) {
      const ny = impl.getTimeZonesAt(ts).find((z) => z.name === 'America/New_York')!;
      expect(ny.abbr).toBe('EDT');
      expect(ny.offset).toBe('-04:00');
    }
  });
});
