import { describe, test, expect } from 'bun:test';
import { getTimeZonesAt as baked07, clearCache as clear07 } from '../impls/07-baked-rules/index.ts';
import { getTimeZonesAt as audited10, clearCache as clear10 } from '../impls/10-audited-rules/index.ts';
import { getTimeZonesAt as baseline04, clearCache as clear04 } from '../impls/04-live-intl/index.ts';
import { scheduleClasses, genMeta, YEAR_START, STEP_MS } from '../shared/schedule.ts';
import { resolveClass, buildScheduleIndex } from '../shared/rules.ts';
import { zones } from '../shared/zones.ts';

// Coverage for the historical eras (shared/history.ts) integrated into the
// rule-baking impls (07, 10). Each "tricky" instant is a case the 0.1.1
// tables got WRONG: 0.1.1's impl 07 projected the current nth-weekday /
// static rules backwards, so a pre-regime-change instant resolved to today's
// offset instead of the one actually in force. We reconstruct that exact
// 0.1.1 answer with `legacyOffset` (resolveClass alone, no history) and prove
// it diverges from ICU, while the history-backed impls now match ICU.
//
// Equivalence against live Intl is only meaningful when this runtime's ICU
// matches the one the tables were generated from (same gate as
// schedule.test.ts); Chrome-generated tables are checked in-browser.
const aligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
const testIfAligned = aligned ? test : test.skip;

if (!aligned) {
  console.warn(`  [history.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl equivalence`);
}

// zones-list order -> schedule class, for reproducing the 0.1.1 (history-less)
// answer: resolveClass with the year-independent rules only.
const classIdx = buildScheduleIndex(zones, scheduleClasses);
const zoneIdx = new Map(zones.map((z, i) => [z, i]));

// signed-minutes offset, matching TimeZoneInfo.offset
function legacyOffset(zone: string, ts: number): number {
  const ci = classIdx[zoneIdx.get(zone)!]!;
  return resolveClass(scheduleClasses[ci]!, ts, YEAR_START, STEP_MS).offMin;
}

function rec(get: (t: number) => { name: string; offset: number; abbr: string }[], clear: () => void, zone: string, ts: number) {
  clear();
  return get(ts).find((z) => z.name === zone)!;
}

const icu = (zone: string, ts: number) => rec(baseline04, clear04, zone, ts);
const baked = (zone: string, ts: number) => rec(baked07, clear07, zone, ts);
const audited = (zone: string, ts: number) => rec(audited10, clear10, zone, ts);

// instants where 0.1.1's backward projection produced the WRONG offset
const tricky: { label: string; zone: string; ts: number }[] = [
  // US pre-2007 DST: spring-forward was the 1st Sunday of April (Apr 3, 2005),
  // not the 2nd Sunday of March that today's rule projects — so mid-March is
  // still EST. 0.1.1 projected EDT.
  { label: 'America/New_York before pre-2007 spring-forward (2005-03-20)', zone: 'America/New_York', ts: Date.UTC(2005, 2, 20, 12) },
  // US pre-2007 DST: fall-back was the last Sunday of October (Oct 30, 2005),
  // not the 1st Sunday of November — so early November is already EST. 0.1.1
  // projected EDT.
  { label: 'America/New_York after pre-2007 fall-back (2005-11-01)', zone: 'America/New_York', ts: Date.UTC(2005, 10, 1, 12) },
  // Bangladesh observed DST only in 2009 (+07); the current table has no DST
  // for Dhaka, so 0.1.1 projected the +06 standard offset year-round. This is
  // also the single-year rule whose 2nd transition wrapped past year-end and
  // is baked as a raw-year era.
  { label: 'Asia/Dhaka during its one-off 2009 DST (+07)', zone: 'Asia/Dhaka', ts: Date.UTC(2009, 7, 15, 6) },
  // Pacific/Kosrae ran at +12 until 1999-01-01, then switched to +11 (its
  // current, static offset). 0.1.1's static class projected +11 back through
  // the 1990s; the late-Dec year-end transition also stressed the generator's
  // per-year signature probe.
  { label: 'Pacific/Kosrae in its pre-1999 +12 era', zone: 'Pacific/Kosrae', ts: Date.UTC(1998, 5, 15, 12) },
];

// ordinary historical instants: the projection was already right here
// (post-2007 US, EU stable since 1996, southern summer), so history defers to
// the schedule and nothing regressed.
const normal: { label: string; zone: string; ts: number }[] = [
  { label: 'America/New_York summer 2015 (EDT)', zone: 'America/New_York', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'America/New_York winter 2015 (EST)', zone: 'America/New_York', ts: Date.UTC(2015, 0, 15, 12) },
  { label: 'Europe/London summer 2000 (BST, EU stable since 1996)', zone: 'Europe/London', ts: Date.UTC(2000, 6, 15, 12) },
  { label: 'Europe/Paris summer 2015 (CEST)', zone: 'Europe/Paris', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'Australia/Sydney summer 2015 (AEDT)', zone: 'Australia/Sydney', ts: Date.UTC(2015, 0, 15, 0) },
];

describe('history eras fix offsets 0.1.1 projected wrong', () => {
  for (const { label, zone, ts } of tricky) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts).offset;

      // the history-backed impls agree with live ICU...
      expect(baked(zone, ts).offset).toBe(truth);
      expect(audited(zone, ts).offset).toBe(truth); // no-Temporal here => baked path

      // ...and the history-less 0.1.1 projection did NOT (regression guard:
      // if this ever stops diverging the case is no longer exercising history)
      expect(legacyOffset(zone, ts)).not.toBe(truth);
    });
  }
});

describe('ordinary historical instants stay correct (history defers to schedule)', () => {
  for (const { label, zone, ts } of normal) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts);

      // full record (offset + abbr) matches live ICU for the common case
      const b = baked(zone, ts);
      expect(b.offset).toBe(truth.offset);
      expect(b.abbr).toBe(truth.abbr);
      expect(audited(zone, ts)).toEqual(b);

      // and the projection was already right here — no divergence
      expect(legacyOffset(zone, ts)).toBe(truth.offset);
    });
  }
});

describe('era boundaries switch regimes at the right year', () => {
  // Kosrae flips +12 -> +11 across the 1999 boundary; both sides match ICU
  testIfAligned('Pacific/Kosrae +12 (1998) -> +11 (1999)', () => {
    const before = baked('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset;
    const after = baked('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset;

    expect(before).toBe(icu('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset);
    expect(after).toBe(icu('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset);
    expect(before).not.toBe(after);
  });
});
