import { describe, test, expect } from 'bun:test';
import { getTimeZonesAt as baked07, getTimeZoneAt as bakedAt07, clearCache as clear07 } from '../impls/07-baked-rules/index.ts';
import { getTimeZonesAt as audited10, getTimeZoneAt as auditedAt10, clearCache as clear10 } from '../impls/10-audited-rules/index.ts';
import { getTimeZonesAt as baseline04, getTimeZoneAt as baselineAt04, clearCache as clear04 } from '../impls/04-live-intl/index.ts';
import { scheduleClasses, genMeta, YEAR_START, STEP_MS } from '../shared/schedule.ts';
import { resolveClass, buildScheduleIndex } from '../shared/rules.ts';
import { zones } from '../shared/zones.ts';
import { SCHEDULE_STRIDE_DAYS, HISTORY_STRIDE_DAYS } from '../tools/gen-core.ts';

// Coverage for the historical eras (shared/history.ts) integrated into the
// rule-baking impls (07, 10). Each "tricky" instant is a case the 0.1.1
// tables got WRONG: 0.1.1's impl 07 projected the current nth-weekday /
// static rules backwards, so a pre-regime-change instant resolved to today's
// offset instead of the one actually in force. We reconstruct that exact
// 0.1.1 answer with `legacyOffset` (resolveClass alone, no history) and prove
// it diverges from ICU, while the history-backed impls now match ICU.
//
// Equivalence against live Intl is only meaningful when this runtime's ICU
// matches the one the tables were generated from (same gate as
// schedule.test.ts); Chrome-generated tables are checked in-browser.
const aligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
const testIfAligned = aligned ? test : test.skip;
// known gaps: fails today, and bun flags it the moment it starts passing so
// remediation can't land silently
const testFailingIfAligned = aligned ? test.failing : test.skip;

if (!aligned) {
  console.warn(`  [history.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl equivalence`);
}

// zones-list order -> schedule class, for reproducing the 0.1.1 (history-less)
// answer: resolveClass with the year-independent rules only.
const classIdx = buildScheduleIndex(zones, scheduleClasses);
const zoneIdx = new Map(zones.map((z, i) => [z, i]));

// signed-minutes offset, matching TimeZoneInfo.offset
function legacyOffset(zone: string, ts: number): number {
  const ci = classIdx[zoneIdx.get(zone)!]!;
  return resolveClass(scheduleClasses[ci]!, ts, YEAR_START, STEP_MS).offMin;
}

function rec(get: (t: number) => { name: string; offset: number; abbr: string }[], clear: () => void, zone: string, ts: number) {
  clear();
  return get(ts).find((z) => z.name === zone)!;
}

const icu = (zone: string, ts: number) => rec(baseline04, clear04, zone, ts);
const baked = (zone: string, ts: number) => rec(baked07, clear07, zone, ts);
const audited = (zone: string, ts: number) => rec(audited10, clear10, zone, ts);

// the single-zone getters resolve through the same cores without building or
// memoizing the whole response, so they're the ones to use when walking many
// instants (single-zone.test.ts pins them to the list getters)
const icuOff = (zone: string, ts: number) => baselineAt04(zone, ts).offset;
const bakedOff = (zone: string, ts: number) => bakedAt07(zone, ts).offset;
const auditedOff = (zone: string, ts: number) => auditedAt10(zone, ts).offset;

// instants where 0.1.1's backward projection produced the WRONG offset
const tricky: { label: string; zone: string; ts: number }[] = [
  // US pre-2007 DST: spring-forward was the 1st Sunday of April (Apr 3, 2005),
  // not the 2nd Sunday of March that today's rule projects — so mid-March is
  // still EST. 0.1.1 projected EDT.
  { label: 'America/New_York before pre-2007 spring-forward (2005-03-20)', zone: 'America/New_York', ts: Date.UTC(2005, 2, 20, 12) },
  // US pre-2007 DST: fall-back was the last Sunday of October (Oct 30, 2005),
  // not the 1st Sunday of November — so early November is already EST. 0.1.1
  // projected EDT.
  { label: 'America/New_York after pre-2007 fall-back (2005-11-01)', zone: 'America/New_York', ts: Date.UTC(2005, 10, 1, 12) },
  // Bangladesh observed DST only in 2009 (+07); the current table has no DST
  // for Dhaka, so 0.1.1 projected the +06 standard offset year-round. This is
  // also the single-year rule whose 2nd transition wrapped past year-end and
  // is baked as a raw-year era.
  { label: 'Asia/Dhaka during its one-off 2009 DST (+07)', zone: 'Asia/Dhaka', ts: Date.UTC(2009, 7, 15, 6) },
  // Pacific/Kosrae ran at +12 until 1999-01-01, then switched to +11 (its
  // current, static offset). 0.1.1's static class projected +11 back through
  // the 1990s; the late-Dec year-end transition also stressed the generator's
  // per-year signature probe.
  { label: 'Pacific/Kosrae in its pre-1999 +12 era', zone: 'Pacific/Kosrae', ts: Date.UTC(1998, 5, 15, 12) },
  // Cambridge_Bay spent the 2000 Nunavut experiment on Eastern time (-300)
  // while its modern class is Mountain (-420/-360), so 0.1.1 projected -360
  // for this week. See the dedicated block below for why this week in
  // particular is the one that pins the generator's scan stride.
  { label: 'America/Cambridge_Bay during the 2000 Nunavut experiment (EST)', zone: 'America/Cambridge_Bay', ts: Date.UTC(2000, 10, 1, 12) },
];

// ordinary historical instants: the projection was already right here
// (post-2007 US, EU stable since 1996, southern summer), so history defers to
// the schedule and nothing regressed.
const normal: { label: string; zone: string; ts: number }[] = [
  { label: 'America/New_York summer 2015 (EDT)', zone: 'America/New_York', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'America/New_York winter 2015 (EST)', zone: 'America/New_York', ts: Date.UTC(2015, 0, 15, 12) },
  { label: 'Europe/London summer 2000 (BST, EU stable since 1996)', zone: 'Europe/London', ts: Date.UTC(2000, 6, 15, 12) },
  { label: 'Europe/Paris summer 2015 (CEST)', zone: 'Europe/Paris', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'Australia/Sydney summer 2015 (AEDT)', zone: 'Australia/Sydney', ts: Date.UTC(2015, 0, 15, 0) },
];

describe('history eras fix offsets 0.1.1 projected wrong', () => {
  for (const { label, zone, ts } of tricky) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts).offset;

      // the history-backed impls agree with live ICU...
      expect(baked(zone, ts).offset).toBe(truth);
      expect(audited(zone, ts).offset).toBe(truth); // no-Temporal here => baked path

      // ...and the history-less 0.1.1 projection did NOT (regression guard:
      // if this ever stops diverging the case is no longer exercising history)
      expect(legacyOffset(zone, ts)).not.toBe(truth);
    });
  }
});

describe('ordinary historical instants stay correct (history defers to schedule)', () => {
  for (const { label, zone, ts } of normal) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts);

      // full record (offset + abbr) matches live ICU for the common case
      const b = baked(zone, ts);
      expect(b.offset).toBe(truth.offset);
      expect(b.abbr).toBe(truth.abbr);
      expect(audited(zone, ts)).toEqual(b);

      // and the projection was already right here — no divergence
      expect(legacyOffset(zone, ts)).toBe(truth.offset);
    });
  }
});

// America/Cambridge_Bay's 2000 Nunavut experiment holds the tightest pair of
// consecutive transitions anywhere in tzdata: a name-only CDT -> EST flip on
// Oct 29 (the offset stays at -300) followed 6.92 days later by the real
// fall-back to CST. That 6.92d gap is the floor the generator's linear scan
// stride has to stay under — tools/tz-transition-gap.ts measures it across all
// of tzdata and asserts it against the strides imported here.
//
// A stride wide enough to bracket both transitions is where the scan runs out
// of room. It resolves several changes per window, so the danger isn't two
// transitions sharing one — it's a window whose endpoints agree while
// something happened in between, which no sampling can detect. Both ends of
// this week read -300 the moment a window spans it, so only the interior —
// what these cases walk — can catch that.
const CB = 'America/Cambridge_Bay';
const CB_NAME_FLIP = Date.UTC(2000, 9, 29, 7); // CDT -> EST; offset unchanged at -300
const CB_FALL_BACK = Date.UTC(2000, 10, 5, 5); // EST -> CST; -300 -> -360

describe('the tightest transition pair in tzdata (America/Cambridge_Bay, 2000)', () => {
  testIfAligned('the name-only CDT -> EST flip leaves the offset alone', () => {
    for (const ts of [CB_NAME_FLIP - STEP_MS, CB_NAME_FLIP]) {
      expect(icuOff(CB, ts)).toBe(-300);
      expect(bakedOff(CB, ts)).toBe(-300);
      expect(auditedOff(CB, ts)).toBe(-300);
    }
  });

  testIfAligned('the whole 6.92d week between the two transitions stays at -300', () => {
    for (let ts = CB_NAME_FLIP; ts < CB_FALL_BACK; ts += STEP_MS) {
      expect(icuOff(CB, ts)).toBe(-300);
      expect(bakedOff(CB, ts)).toBe(-300);
      expect(auditedOff(CB, ts)).toBe(-300);
    }
  });

  testIfAligned('the fall-back edge is exact to the 15-minute step', () => {
    for (const off of [icuOff, bakedOff, auditedOff]) {
      expect(off(CB, CB_FALL_BACK - STEP_MS)).toBe(-300);
      expect(off(CB, CB_FALL_BACK)).toBe(-360);
    }
  });

  // guards the strategy itself rather than its current output: the cases above
  // only prove the scan resolves this pair today, and they'd keep passing if a
  // future stride change re-broke a DIFFERENT zone's tight pair
  test('the generator scans finer than this gap', () => {
    const gapDays = (CB_FALL_BACK - CB_NAME_FLIP) / 86_400_000;

    expect(gapDays).toBeCloseTo(6.92, 2);
    expect(SCHEDULE_STRIDE_DAYS).toBeLessThan(gapDays);
    expect(HISTORY_STRIDE_DAYS).toBeLessThan(gapDays);
  });
});

// KNOWN GAP — the history table stores offsets only, so it cannot represent a
// transition that changes only the CLDR name. Below the bake year, abbrs come
// from historyAbbr(), which keys off the resolved offset alone:
//
//   const abbr = ci < 0 ? gmtLabel(off) : historyAbbr(scheduleClasses[ci]!, off);
//
// That makes the label a pure function of the offset, so the baked impls emit
// exactly ONE abbr per run of constant offset. A name-only flip splits such a
// run into two differently-named halves, and no offset-keyed lookup can serve
// both — at least one half is always wrong.
//
// This is a table-format limit, not a probing one: the generator's scan
// resolves these flips exactly (that's what the Cambridge_Bay block above
// walks), then probeOffSegs() drops the names and merges the equal-offset
// segments before anything reaches shared/history.ts.
//
// There are 102 such flips across 1995-2028 in this ICU; the eight below cover
// the distinct shapes. Two fail on both sides, three only after the flip and
// three only before, depending on which half the surviving label happens to
// describe. historyAbbr() falls back to GMT±N only when the historical offset
// matches no state of the modern class (Cambridge_Bay); the rest match a state
// belonging to an identity the zone has since left, so the wrong answer comes
// back with full confidence (Ciudad_Juarez was on Central in 1998, but -360
// matches its modern Mountain class's MDT state).
//
// The 2026+ schedule path is unaffected — it stores per-state and per-segment
// abbrs, and the scan finds no name-only flips inside the bake window.
const nameOnly: { label: string; zone: string; ts: number; before: string; after: string; offset: number }[] = [
  // the Nunavut experiment again: -300 matches neither MST (-420) nor MDT
  // (-360), so this one at least degrades to an honest GMT label
  { label: 'America/Cambridge_Bay CDT -> EST (2000 Nunavut experiment)', zone: CB, ts: CB_NAME_FLIP, before: 'CDT', after: 'EST', offset: -300 },
  // Ciudad_Juarez sat on Central in 1998; its modern class is Mountain, and
  // -360 collides with that class's DST state
  { label: 'America/Ciudad_Juarez CST -> MPDT (1998)', zone: 'America/Ciudad_Juarez', ts: Date.UTC(1998, 3, 5, 9), before: 'CST', after: 'MPDT', offset: -360 },
  // the longest stale window of the 102: Argentina held -180 across this flip
  // and the one back to ART in Mar 2000, so no offset change re-derives the
  // label for over a year
  { label: 'America/Argentina/Buenos_Aires ART -> AST (1999)', zone: 'America/Argentina/Buenos_Aires', ts: Date.UTC(1999, 9, 3, 3), before: 'ART', after: 'AST', offset: -180 },
  // Libya left CEST for a permanent EET without moving off +120
  { label: 'Africa/Tripoli CEST -> EET (1997)', zone: 'Africa/Tripoli', ts: Date.UTC(1997, 9, 3, 22), before: 'CEST', after: 'EET', offset: 120 },
  // the handover renamed Macau time; +480 never budged
  { label: 'Asia/Macau MST -> CST (1999 handover)', zone: 'Asia/Macau', ts: Date.UTC(1999, 11, 19, 16), before: 'MST', after: 'CST', offset: 480 },
  { label: 'Pacific/Guam GST -> ChST (2000)', zone: 'Pacific/Guam', ts: Date.UTC(2000, 11, 22, 14), before: 'GST', after: 'ChST', offset: 600 },
  // Metlakatla left Alaska DST for Pacific standard at the same -480
  { label: 'America/Metlakatla AKDT -> PST (2018)', zone: 'America/Metlakatla', ts: Date.UTC(2018, 10, 4, 10), before: 'AKDT', after: 'PST', offset: -480 },
  // the Yukon's permanent-DST switch: -420 was relabelled from PDT to MST
  { label: 'America/Dawson PDT -> MST (2020 permanent DST)', zone: 'America/Dawson', ts: Date.UTC(2020, 10, 1, 7), before: 'PDT', after: 'MST', offset: -420 },
];

describe('name-only transitions are invisible to the offset-only history table', () => {
  // fixture integrity, kept OUT of the .failing cases below so that a CLDR
  // rename can't quietly satisfy them by breaking the premise instead
  testIfAligned('each fixture really is a name-only flip in live ICU', () => {
    for (const { label, zone, ts, before, after, offset } of nameOnly) {
      const b = icu(zone, ts - STEP_MS);
      const a = icu(zone, ts);

      // label rides along so a drifted fixture names itself in the diff
      expect([label, b.abbr, b.offset]).toEqual([label, before, offset]);
      expect([label, a.abbr, a.offset]).toEqual([label, after, offset]);
    }
  });

  for (const { label, zone, ts, before, after } of nameOnly) {
    testFailingIfAligned(label, () => {
      // impl 10 shares historyAbbr() below the bake year, so it inherits this
      expect(audited(zone, ts - STEP_MS).abbr).toBe(baked(zone, ts - STEP_MS).abbr);
      expect(audited(zone, ts).abbr).toBe(baked(zone, ts).abbr);

      expect(baked(zone, ts - STEP_MS).abbr).toBe(before);
      expect(baked(zone, ts).abbr).toBe(after);
    });
  }
});

describe('era boundaries switch regimes at the right year', () => {
  // Kosrae flips +12 -> +11 across the 1999 boundary; both sides match ICU
  testIfAligned('Pacific/Kosrae +12 (1998) -> +11 (1999)', () => {
    const before = baked('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset;
    const after = baked('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset;

    expect(before).toBe(icu('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset);
    expect(after).toBe(icu('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset);
    expect(before).not.toBe(after);
  });
});
