import { describe, test, expect } from 'bun:test';
import { getTimeZoneAt as one07, getTimeZonesAt as all07, clearCache as clear07 } from '../impls/07-baked-rules/index.ts';
import { getTimeZonesAt as all04, clearCache as clear04 } from '../impls/04-live-intl/index.ts';
import { scheduleClasses, YEAR_START, STEP_MS, genMeta } from '../shared/schedule.ts';
import { alignedWith } from './aligned.ts';
import { resolveClass } from '../shared/rules.ts';
import { classIdx, zoneIndexOf, scheduleZoneInfo } from '../shared/bakedSchedule.ts';
import { HISTORY_TO_MS } from '../shared/bakedHistory.ts';
import { zones } from '../shared/zones.ts';
import { zoneLinkPairs } from '../shared/zoneLinks.ts';

// Guards for the two per-class caches that back resolution (shared/rules.ts)
// and the (zone, state) identity cache in front of the intern pool
// (shared/bakedSchedule.ts). All three are shared mutable state living for the
// process lifetime, so the risks they introduce are NOT about a single answer
// being wrong — the fixtures and equivalence suites cover that — but about an
// answer depending on what was asked before it. These pin that down.

// the live-Intl oracle below is only valid when the tables were generated by
// this runtime's ICU (same gate as schedule.test.ts / dst.test.ts)
const testIfAligned = alignedWith(genMeta) ? test : test.skip;

const instants = [
  Date.UTC(2026, 0, 15, 12),
  Date.UTC(2026, 6, 15, 12),
  Date.UTC(2027, 2, 10, 12),
  Date.UTC(2028, 6, 15, 12),
  Date.UTC(2026, 10, 1, 5, 30),
];

describe('resolveClass returns the schedule-owned state object', () => {
  // shared/bakedSchedule.ts keys a cache on this object's identity, so a class
  // must hand back the SAME instance for the same state — including kind 2,
  // which used to build a fresh one per call
  test('every class kind is identity-stable across calls', () => {
    const seen = new Set<number>();

    for (const cls of scheduleClasses) {
      seen.add(cls.kind);

      for (const ts of instants) {
        expect(resolveClass(cls, ts, YEAR_START, STEP_MS)).toBe(resolveClass(cls, ts, YEAR_START, STEP_MS));
      }
    }

    expect([...seen].sort((a, b) => a - b)).toEqual([0, 1, 2]); // all three kinds actually exercised
  });

  test('a class yields only as many distinct states as it has', () => {
    // an unbounded set would mean the identity cache grows per call
    for (const cls of scheduleClasses) {
      const states = new Set(instants.map((ts) => resolveClass(cls, ts, YEAR_START, STEP_MS)));
      const max = cls.kind === 0 ? 1 : cls.kind === 1 ? 2 : cls.starts.length;

      expect(states.size).toBeLessThanOrEqual(max);
    }
  });
});

describe('answers do not depend on the order they were asked in', () => {
  // The kind-1 transition cache is a SINGLE slot keyed by year: querying one
  // year evicts another. Grouping by year maximizes hits and interleaving
  // maximizes evictions, so a stale read makes the two disagree.
  //
  // Probes sit in the changeover windows, where a year's DST dates drift by up
  // to a week — that's where reading another year's instants actually changes
  // the answer. Mid-January/July would mask it.
  const years = [2026, 2027, 2005, 2026, 1998, 2027];
  const probes = years.flatMap((y) =>
    [
      [2, 8], [2, 14], [2, 29], // northern spring forward (US, then EU)
      [9, 25], [10, 1], [10, 7], // northern fall back
      [3, 5], [8, 28], // southern hemisphere changeovers
    ].map(([mon, day]) => Date.UTC(y, mon, day, 9))
  );

  test('interleaved years match year-grouped queries', () => {
    const grouped = new Map<string, string>();

    for (const ts of probes) {
      for (const name of zones) grouped.set(`${name}@${ts}`, JSON.stringify(one07(name, ts)));
    }

    for (const name of zones) {
      for (const ts of probes) {
        expect(JSON.stringify(one07(name, ts))).toBe(grouped.get(`${name}@${ts}`)!);
      }
    }
  });

  // Ordering alone can't see a slot that never refreshes at all — that is
  // wrong identically in every order — so pin the interleaved answers to live
  // Intl. The oracle is collected up front, per instant; only the 07 sweep
  // that reads it is interleaved, which is where the cache thrashes.
  testIfAligned('interleaved answers still match live Intl', () => {
    const oracleProbes = probes.filter((ts) => new Date(ts).getUTCFullYear() !== 1998).slice(0, 18);
    const oracle = new Map<string, string>();

    for (const ts of oracleProbes) {
      clear04();
      for (const z of all04(ts)) oracle.set(`${z.name}@${ts}`, `${z.abbr} ${z.offset}`);
    }

    // the irregular classes hold only the generated year's segments and clamp
    // outside it, so the Ramadan-rule zones knowingly diverge in other years
    // (see tools/sweep-validity.ts); that's orthogonal to caching
    const irregular = new Set(scheduleClasses.filter((c) => c.kind === 2).flatMap((c) => c.zones));

    // Before the bake year the answer comes from the historical eras, which
    // store OFFSETS only and label an offset the schedule class doesn't have
    // with a generic GMT form (see shared/bakedHistory.ts) — so compare labels
    // only from the bake year on. The offset is the signal that matters here
    // anyway: picking the wrong side of a transition always moves it.
    const strip = (v: string, historical: boolean) => (historical ? v.slice(v.indexOf(' ') + 1) : v);

    for (const name of zones) {
      if (irregular.has(name)) continue;

      for (const ts of oracleProbes) {
        const historical = ts < HISTORY_TO_MS;
        const info = one07(name, ts);

        expect(`${name}@${ts} ${strip(`${info.abbr} ${info.offset}`, historical)}`).toBe(
          `${name}@${ts} ${strip(oracle.get(`${name}@${ts}`)!, historical)}`
        );
      }
    }
  });

  test('a zone resolved alone matches the same zone inside a full response', () => {
    for (const ts of instants) {
      clear07();

      for (const info of all07(ts)) expect(one07(info.name, ts)).toBe(info); // same instance, not just equal
    }
  });
});

describe('the (zone, state) cache cannot leak a name across spellings', () => {
  // It is keyed by zones-list index, but a bridged alias resolves to the
  // CANONICAL zone's index while still owing the caller its own spelling, so
  // scheduleZoneInfo() honors the index only when the name really is zones[z].
  //
  // This runtime enumerates both spellings of every link pair, so no lookup
  // actually bridges here (asserted below — if that ever changes, the natural
  // case is worth covering too). Chrome's narrower enumeration does bridge, so
  // the guard is driven directly.
  const ts = Date.UTC(2026, 6, 15, 12);

  test('nothing bridges on this runtime, so the guard is driven directly', () => {
    const unenumerated = zoneLinkPairs.flat().filter((n) => !zones.includes(n));

    expect(unenumerated).toEqual([]);
  });

  test('a mismatched name is answered under its own spelling, not the cached one', () => {
    const z = zoneIndexOf('Asia/Kolkata');
    const canonical = scheduleZoneInfo('Asia/Kolkata', classIdx[z]!, ts, undefined, z); // populates index z

    const alias = scheduleZoneInfo('Some/Alias', classIdx[z]!, ts, undefined, z);

    expect(alias.name).toBe('Some/Alias');
    expect(alias.abbr).toBe(canonical.abbr);
    expect(alias.offset).toBe(canonical.offset);

    // and the real entry at that index is untouched by the mismatched call
    expect(scheduleZoneInfo('Asia/Kolkata', classIdx[z]!, ts, undefined, z)).toBe(canonical);
  });
});
