import { describe, test, expect } from 'bun:test';
import { getTimeZonesAt as precomputed, clearCache as clear07 } from '../impls/07-precomputed/index.ts';
import { getTimeZonesAt as baseline, clearCache as clear04 } from '../impls/04-intl-single-fmt/index.ts';
import { scheduleClasses, genMeta } from '../shared/schedule.ts';
import { scheduleOffsets } from '../shared/offsets.ts';
import { zones } from '../shared/zones.ts';
import { fixtures } from '../shared/fixtures.ts';

const YEAR = 2026;

// equivalence against live Intl is only meaningful when this runtime's ICU
// matches the one the tables were generated from (see genMeta provenance);
// Chrome-generated tables are verified in-browser by tools/gen-chrome.ts
const aligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
const testIfAligned = aligned ? test : test.skip;

if (!aligned) {
  console.warn(`  [schedule.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl equivalence`);
}

// both impls memoize per hour bucket; clear between comparisons so each ts
// is computed fresh by both sides
function both(ts: number) {
  clear04();
  clear07();
  return [precomputed(ts), baseline(ts)] as const;
}

describe('07-precomputed equivalence with 04 baseline', () => {
  testIfAligned('schedule table covers exactly the runtime zone list, no duplicates', () => {
    const seen = new Set<string>();
    const known = new Set(zones);

    expect(scheduleOffsets.length).toBe(scheduleClasses.length);

    for (let ci = 0; ci < scheduleClasses.length; ci++) {
      const c = scheduleClasses[ci]!;

      expect(c.starts.length).toBe(c.abbrs.length);
      expect(c.starts.length).toBe(scheduleOffsets[ci]!.length);
      expect(c.starts[0]).toBe(0); // every class covers the year start

      for (const z of c.zones) {
        expect(known.has(z)).toBe(true);
        expect(seen.has(z)).toBe(false);
        seen.add(z);
      }
    }

    expect(seen.size).toBe(zones.length);
  });

  testIfAligned('identical output to 04 at semi-monthly instants across the year', () => {
    for (let m = 0; m < 12; m++) {
      for (const d of [1, 15]) {
        for (const h of [0, 12]) {
          const [a, b] = both(Date.UTC(YEAR, m, d, h));
          expect(a).toEqual(b);
        }
      }
    }
  });

  testIfAligned('identical output to 04 at all DST fixture instants', () => {
    for (const f of fixtures) {
      const [a, b] = both(f.ts);
      expect(a).toEqual(b);
    }
  });

  testIfAligned('identical output to 04 around 2026 US/EU/AU transition instants', () => {
    const transitions = [
      Date.UTC(YEAR, 2, 8, 7), // US spring-forward
      Date.UTC(YEAR, 2, 29, 1), // EU spring-forward
      Date.UTC(YEAR, 3, 4, 16), // Sydney fall-back
      Date.UTC(YEAR, 9, 3, 16), // Sydney spring-forward
      Date.UTC(YEAR, 9, 25, 1), // EU fall-back
      Date.UTC(YEAR, 10, 1, 6), // US fall-back
    ];

    for (const t of transitions) {
      for (const delta of [-60_000, 0, 60_000]) {
        const [a, b] = both(t + delta);
        expect(a).toEqual(b);
      }
    }
  });

  test('timestamps outside the generated year clamp instead of throwing', () => {
    clear07();
    const before = precomputed(Date.UTC(YEAR - 1, 11, 31, 23));
    clear07();
    const after = precomputed(Date.UTC(YEAR + 1, 0, 1, 1));

    expect(before.length).toBe(zones.length);
    expect(after.length).toBe(zones.length);

    // clamped edges resolve to the year's first/last segments
    clear07();
    expect(before).toEqual(precomputed(Date.UTC(YEAR, 0, 1, 0)));
  });
});
