import { describe, test, expect } from 'bun:test';
import { getTimeZonesAt as precomputed, clearCache as clear07 } from '../impls/07-precomputed/index.ts';
import { getTimeZonesAt as baseline, clearCache as clear04 } from '../impls/04-intl-single-fmt/index.ts';
import { scheduleClasses, genMeta } from '../shared/schedule.ts';
import { zones } from '../shared/zones.ts';
import { fixtures } from '../shared/fixtures.ts';

const YEAR = 2026;

// equivalence against live Intl is only meaningful when this runtime's ICU
// matches the one the tables were generated from (see genMeta provenance);
// Chrome-generated tables are verified in-browser by tools/gen-chrome.ts
const aligned = genMeta.host === `bun ${Bun.version}` && genMeta.icu === process.versions.icu;
const testIfAligned = aligned ? test : test.skip;

if (!aligned) {
  console.warn(`  [schedule.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl equivalence`);
}

// both impls memoize per hour bucket; clear between comparisons so each ts
// is computed fresh by both sides
function both(ts: number) {
  clear04();
  clear07();
  return [precomputed(ts), baseline(ts)] as const;
}

describe('07-precomputed equivalence with 04 baseline', () => {
  testIfAligned('schedule table covers exactly the runtime zone list, well-formed classes', () => {
    const seen = new Set<string>();
    const known = new Set(zones);

    for (const c of scheduleClasses) {
      if (c.kind === 0) {
        expect(c.states.length).toBe(1);
      } else if (c.kind === 1) {
        expect(c.states.length).toBe(2);
        expect(c.rules.length).toBe(2);
        expect(c.rules[0].month).toBeLessThan(c.rules[1].month);

        for (const r of c.rules) {
          expect(r.month).toBeGreaterThanOrEqual(1);
          expect(r.month).toBeLessThanOrEqual(12);
          expect(r.nth).toBeGreaterThanOrEqual(1);
          expect(r.nth).toBeLessThanOrEqual(5);
          expect(r.dow).toBeGreaterThanOrEqual(0);
          expect(r.dow).toBeLessThanOrEqual(6);
        }

        // the two rules must switch to different states
        expect(c.rules[0].to).not.toBe(c.rules[1].to);
      } else {
        expect(c.starts[0]).toBe(0);
        expect(c.starts.length).toBe(c.abbrs.length);
        expect(c.starts.length).toBe(c.offMins.length);
      }

      for (const z of c.zones) {
        expect(known.has(z)).toBe(true);
        expect(seen.has(z)).toBe(false);
        seen.add(z);
      }
    }

    expect(seen.size).toBe(zones.length);
  });

  testIfAligned('identical output to 04 at semi-monthly instants across the year', () => {
    for (let m = 0; m < 12; m++) {
      for (const d of [1, 15]) {
        for (const h of [0, 12]) {
          const [a, b] = both(Date.UTC(YEAR, m, d, h));
          expect(a).toEqual(b);
        }
      }
    }
  });

  testIfAligned('identical output to 04 at all DST fixture instants', () => {
    for (const f of fixtures) {
      const [a, b] = both(f.ts);
      expect(a).toEqual(b);
    }
  });

  testIfAligned('identical output to 04 around 2026 US/EU/AU transition instants', () => {
    const transitions = [
      Date.UTC(YEAR, 2, 8, 7), // US spring-forward
      Date.UTC(YEAR, 2, 29, 1), // EU spring-forward
      Date.UTC(YEAR, 3, 4, 16), // Sydney fall-back
      Date.UTC(YEAR, 9, 3, 16), // Sydney spring-forward
      Date.UTC(YEAR, 9, 25, 1), // EU fall-back
      Date.UTC(YEAR, 10, 1, 6), // US fall-back
    ];

    for (const t of transitions) {
      for (const delta of [-60_000, 0, 60_000]) {
        const [a, b] = both(t + delta);
        expect(a).toEqual(b);
      }
    }
  });

  // the payoff of year-independent rules: 07 stays correct past the table's
  // generation year for rule/static zones. irregular zones (non-Gregorian
  // rules: Morocco, Palestine) clamp outside the generated year by design
  // and are excluded here.
  testIfAligned('identical output to 04 in the NEXT year (rules, not clamping)', () => {
    const irregular = new Set<string>();

    for (const c of scheduleClasses) {
      if (c.kind === 2) for (const z of c.zones) irregular.add(z);
    }

    for (const ts of [
      Date.UTC(YEAR + 1, 0, 15, 12), // winter
      Date.UTC(YEAR + 1, 6, 15, 12), // summer — post-US/EU spring-forward
      Date.UTC(YEAR + 1, 2, 14, 8), // 1h after US spring-forward 2027 (Mar 14)
      Date.UTC(YEAR + 1, 2, 28, 2), // 1h after EU spring-forward 2027 (Mar 28)
    ]) {
      const [a, b] = both(ts);

      expect(a.filter((z) => !irregular.has(z.name))).toEqual(b.filter((z) => !irregular.has(z.name)));
    }
  });

  test('timestamps outside the probed range do not throw', () => {
    clear07();
    const before = precomputed(Date.UTC(YEAR - 1, 11, 31, 23));
    clear07();
    const after = precomputed(Date.UTC(YEAR + 5, 0, 1, 1));

    expect(before.length).toBe(zones.length);
    expect(after.length).toBe(zones.length);
  });
});
