// AUTO-GENERATED by tools/gen-abbrfix.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// Historical abbreviation corrections (1995-2025), layered over the
// offset-only history eras. history.ts stores no labels, so below the bake year
// an abbreviation is derived from the resolved OFFSET alone — which is wrong
// wherever a zone's historical identity differs from its modern schedule class
// (America/Ciudad_Juarez was Central in 1998; -360 matches its modern Mountain
// class's MDT). These carry the label live Intl reports, for the instants where
// that answer is a confident lie. Where the offset matches no modern state (so
// the fallback is a vague GMT±N rather than a wrong name) it is NOT corrected.
//
// Keyed by (year range, offset), not by timestamp: the wrong label is itself a
// function of the offset, so a record need only say "in these years this offset
// means X". 529 disagreeing spans collapse to 38 range records; the
// 58 spans that survive cover years where one offset holds two identities.
// 68 zones -> 49 shared payloads, 28 distinct labels
// (32 of the spans land in defer eras, resolved via the schedule class)
// Covers 361 zone-years that would otherwise be mislabelled.
// Consumed via shared/rules.ts resolveAbbrFix (tests/history.test.ts pins it).
// generated by: bun 1.4.0, 2026-07-27T14:11:48.735Z

import { decodeAbbrFix } from '../../decode.ts';
import { scheduleClasses, STEP_MS } from './schedule.ts';

export const genMeta = {
  "host": "bun 1.4.0",
  "icu": "75.1",
  "generated": "2026-07-27T14:11:48.735Z"
} as const;

export const ABBRFIX_FROM = 1995;

// same zone-index space as history.ts. The eager decode is /*@__PURE__*/ so a
// bundler drops this table whenever nothing references abbrFixClasses — which
// is every schedule-only entry point, since only shared/bakedHistory.ts reads it.
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const A = 'CEST,WAST,AST,MDT,CST,CDT,MPDT,PDT,WGST,EST,PST,EGST,MAGT,MST,GMT+5,GMT+6,EET,PKST,NOVT,NST,QST,SST,GST,FIST,CET,EEST,FET,NMIT';
const F = '1h~~1p18,djw,0;bmw8,fk0,0|1d~0,l,1k,1~gag4,fjw,1;bes,3ro,1|2e2f2g2h2i2j2k2l2m2o2p~~3klo,b9c,2|2n~d,0,10,1~3klo,b9c,1;6gys,avw,1|2v~1,d,o,3~|9x~5,0,o,4~3mow,beo,4;g2c,awg,4|2r~4,f,s,5~2ozc,684,5|2x~4,m,o,6~2g6c,f18,6;hm5g,fjw,6|9y~0,2,o,4;4,m,o,6~248s,bxk,4;0,f18,6;hklg,h3w,6;0,2ag,4|3h3n~0,o,k,7~ixd4,hmc,7|3j~0,j,k,7~|b4~0,s,14,8~l7s4,r40,8|af~k,2,w,2~f60s,29eo,2|a3a4~0,a,s,9~0,8ge4,9|aiak~~8ge4,fk0,5;9us,hmk,5|al~~8ge4,fk0,5|am~~3y3k,fjw,5|ao~0,4,s,5~3y3k,fjw,5|9r~0,k,g,a~hx2g,5pc,a|a7~0,e,o,3~bf7o,hmk,3|a9~0,7,o,3~67ic,f18,3|aa~4,m,o,3~2g6c,f18,3;hklg,h3w,3|ab~~4dng,bes,9|ac~~4dng,bes,9;46vw,9us,9|b5~0,s,18,b~lnus,beo,b|4o~g,2,2o,c~bg6w,g2s,d;aw0,2oyk,c|4f~0,8,1w,2~6xx4,g2o,2|4g~0,8,1w,2~6mic,beo,2|4h~0,8,1w,e~6xx4,g2o,e|4y~0,9,20,f~7ovq,a7m,f|bg~~gelg,aw0,g|5j~~bg6w,g2s,h|5q~0,3,28,d~0,3qcg,d|5n~g,2,24,i~bg7g,g2s,j;aw0,2oyk,i|5w~0,f,24,j~|4i~0,8,1w,e~6xx4,g2o,e|4j~0,9,1w,e~|4k~0,9,1w,k~|60~3,c,2k,l~1on0,fk4,l|67~~74ng,9cg,m|6h~~67w,dhc,2|6k~0,e,10,n~b17c,gl8,n|bw~0,0,1g,o~jpg,e00,o|7f~0,f,1o,p;g,2,1o,q~c76o,2p14,q|7j~~bg7s,g2s,l|7h~3,f,1o,p~1oo4,fk0,p|bq~~2fms,fk0,0;beo,g2o,0|81~0,4,2g,m~0,4ho8,m|82~0,4,2g,r~0,4ho8,r';

export const abbrFixClasses = /*@__PURE__*/ decodeAbbrFix(Z, A, F, ABBRFIX_FROM, STEP_MS);
