// AUTO-GENERATED by tools/gen-abbrfix.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// Historical abbreviation corrections (1995-2025), layered over the
// offset-only history eras. history.ts stores no labels, so below the bake year
// an abbreviation is derived from the resolved OFFSET alone — which is wrong
// wherever a zone's historical identity differs from its modern schedule class
// (America/Ciudad_Juarez was Central in 1998; -360 matches its modern Mountain
// class's MDT). These carry the label live Intl reports, for the instants where
// that answer is a confident lie. Where the offset matches no modern state (so
// the fallback is a vague GMT±N rather than a wrong name) it is NOT corrected.
//
// Keyed by (year range, offset), not by timestamp: the wrong label is itself a
// function of the offset, so a record need only say "in these years this offset
// means X". 539 disagreeing spans collapse to 40 range records; the
// 58 spans that survive cover years where one offset holds two identities.
// 73 zones -> 51 shared payloads, 30 distinct labels
// (42 of the spans land in defer eras, resolved via the schedule class)
// Covers 369 zone-years that would otherwise be mislabelled.
// Consumed via shared/rules.ts resolveAbbrFix (tests/history.test.ts pins it).
// generated by: bun 1.4.0, 2026-07-27T21:42:30.956Z

import { decodeAbbrFix } from '../../decode.ts';
import { scheduleClasses, STEP_MS } from './schedule.ts';

export const genMeta = {
  "host": "bun 1.4.0",
  "icu": "75.1",
  "generated": "2026-07-27T21:42:30.956Z"
} as const;

export const ABBRFIX_FROM = 1995;

// same zone-index space as history.ts. The eager decode is /*@__PURE__*/ so a
// bundler drops this table whenever nothing references abbrFixClasses — which
// is every schedule-only entry point, since only shared/bakedHistory.ts reads it.
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const A = 'CEST,WAST,AST,MDT,CST,CDT,MPDT,PDT,WGST,EST,PST,CLST,EGST,MAGT,MST,GMT+5,GMT+6,EET,PKST,NOVT,NST,QST,SST,GST,FIST,MSK,CET,EEST,FET,NMIT';
const F = '1h~~1p18,djw,0;bmw8,fk0,0|1d~0,l,1k,1~gag4,fjw,1;bes,3ro,1|2e2f2g2h2i2j2k2l2m2o2p~~3klo,b9c,2|2n~d,0,10,1~3klo,b9c,1;6gys,avw,1|2v~1,d,o,3~|9x~5,0,o,4~3mow,beo,4;g2c,awg,4|2r~4,f,s,5~2ozc,684,5|2x~4,m,o,6~2g6c,f18,6;hm5g,fjw,6|9y~0,2,o,4;4,m,o,6~248s,bxk,4;0,f18,6;hklg,h3w,6;0,2ag,4|3h3n~0,o,k,7~ixd4,hmc,7|3j~0,j,k,7~|b4~0,s,14,8~lslc,6as,8|af~k,2,w,2~f60s,29eo,2|a3a4~0,a,s,9~0,8ge4,9|aiak~~8ge4,fk0,5;9us,hmk,5|al~~8ge4,fk0,5|am~~3y3k,fjw,5|ao~0,4,s,5~3y3k,fjw,5|9r~0,k,g,a~hx2g,5pc,a|a7~0,e,o,3~bf7o,hmk,3|a9~0,7,o,3~67ic,f18,3|aa~4,m,o,3~2g6c,f18,3;hklg,h3w,3|3x3y~k,0,10,b~|ab~~4dng,bes,9|ac~~4dng,bes,9;46vw,9us,9|b5~0,s,18,c~lnus,beo,c|4o~g,2,2o,d~bg6w,g2s,e;vno,246w,d|4f~0,8,1w,2~6xx4,g2o,2|4g~0,8,1w,2~6mic,beo,2|4h~0,8,1w,f~6xx4,g2o,f|4y~0,9,20,g~7ovq,a7m,g|bg~~gelg,aw0,h|5j~~bg6w,g2s,i|5q~0,3,28,e~0,3qcg,e|5n~g,2,24,j~bg7g,g2s,k;vn4,247g,j|5w~0,f,24,k~|4i~0,8,1w,f~6xx4,g2o,f|4j~0,9,1w,f~|4k~0,9,1w,l~|60~3,c,2k,m~1on0,fk4,m|67~~74ng,9cg,n|6h~~67w,dhc,2|6k~0,e,10,o~b17c,gl8,o|777879~h,1,1s,p~|bw~0,0,1g,q~jpg,e00,q|7f~0,f,1o,r;g,2,1o,s~crxc,24ag,s|7j~~bg7s,g2s,m|7h~3,f,1o,r~1oo4,fk0,r|bq~~2fms,fk0,0;beo,g2o,0|81~0,4,2g,n~0,4ho8,n|82~0,4,2g,t~0,4ho8,t';

export const abbrFixClasses = /*@__PURE__*/ decodeAbbrFix(Z, A, F, ABBRFIX_FROM, STEP_MS);
