// AUTO-GENERATED by tools/gen-core.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// Pre-baked signed-offset-minutes -> "±HH:MM" string lookup: the 45
// distinct UTC offsets across the schedule + history tables. formatOffset()
// resolves these with a Map.get and formats on the fly only outside this set.
// generated by: derived from bun schedule + history tables, 2026-07-23T21:59:24.499Z

export const offsetStrings: ReadonlyMap<number, string> = new Map([
  [-720, '-12:00'],
  [-660, '-11:00'],
  [-600, '-10:00'],
  [-570, '-09:30'],
  [-540, '-09:00'],
  [-510, '-08:30'],
  [-480, '-08:00'],
  [-420, '-07:00'],
  [-360, '-06:00'],
  [-300, '-05:00'],
  [-270, '-04:30'],
  [-240, '-04:00'],
  [-210, '-03:30'],
  [-180, '-03:00'],
  [-150, '-02:30'],
  [-120, '-02:00'],
  [-60, '-01:00'],
  [0, '+00:00'],
  [60, '+01:00'],
  [120, '+02:00'],
  [180, '+03:00'],
  [210, '+03:30'],
  [240, '+04:00'],
  [270, '+04:30'],
  [300, '+05:00'],
  [330, '+05:30'],
  [345, '+05:45'],
  [360, '+06:00'],
  [390, '+06:30'],
  [420, '+07:00'],
  [480, '+08:00'],
  [510, '+08:30'],
  [525, '+08:45'],
  [540, '+09:00'],
  [570, '+09:30'],
  [585, '+09:45'],
  [600, '+10:00'],
  [630, '+10:30'],
  [660, '+11:00'],
  [690, '+11:30'],
  [720, '+12:00'],
  [765, '+12:45'],
  [780, '+13:00'],
  [825, '+13:45'],
  [840, '+14:00'],
]);
