// AUTO-GENERATED by tools/gen-abbrfix.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// Historical abbreviation corrections (1995-2025), layered over the
// offset-only history eras. history.ts stores no labels, so below the bake year
// an abbreviation is derived from the resolved OFFSET alone — which is wrong
// wherever a zone's historical identity differs from its modern schedule class
// (America/Ciudad_Juarez was Central in 1998; -360 matches its modern Mountain
// class's MDT). These carry the label live Intl reports, for the instants where
// that answer is a confident lie. Where the offset matches no modern state (so
// the fallback is a vague GMT±N rather than a wrong name) it is NOT corrected.
//
// Keyed by (year range, offset), not by timestamp: the wrong label is itself a
// function of the offset, so a record need only say "in these years this offset
// means X". 675 disagreeing spans collapse to 53 range records; the
// 68 spans that survive cover years where one offset holds two identities.
// 74 zones -> 53 shared payloads, 34 distinct labels
// (32 of the spans land in defer eras, resolved via the schedule class)
// Covers 534 zone-years that would otherwise be mislabelled.
// Consumed via shared/rules.ts resolveAbbrFix (tests/history.test.ts pins it).
// generated by: chrome-headless-shell 151.0.7922.47, 2026-07-27T14:11:55.212Z

import { decodeAbbrFix } from '../../decode.ts';
import { scheduleClasses, STEP_MS } from './schedule.ts';

export const genMeta = {
  "host": "chrome-headless-shell 151.0.7922.47",
  "icu": null,
  "generated": "2026-07-27T14:11:55.212Z"
} as const;

export const ABBRFIX_FROM = 1995;

// same zone-index space as history.ts. The eager decode is /*@__PURE__*/ so a
// bundler drops this table whenever nothing references abbrFixClasses — which
// is every schedule-only entry point, since only shared/bakedHistory.ts reads it.
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const A = 'CEST,GMT+2,AST,WAST,PYST,MDT,CST,CDT,MPDT,PDT,WGST,EST,PST,EGST,ANAT,MST,WKT,GMT+5,GMT+7,GMT+6,EET,NOVT,NST,KST,SAKT,SST,GMT+11,GST,FIST,MSK,CET,EEST,FET,NMIT';
const F = '1h~~1p18,djw,0;bmw8,fk0,0|1d~0,l,1k,1~gag4,fjw,1;bes,3ro,1|2e2f2g2h2j2k2l2m2n2o2p~~3klo,b9c,2|2i~d,0,10,3~3klo,b9c,3;6gys,avw,3|2q~0,s,10,4~llsg,cyk,4;eis,nw,4|2r~1,d,o,5~|96~5,0,o,6~3mow,beo,6;g2c,awg,6|3a~1,0,s,7;4,f,s,7~1p7k,f18,7;kqk,684,7|2t~4,m,o,8~2g6c,f18,8;hm5g,fjw,8|97~0,2,o,6;4,m,o,8~248s,bxk,6;0,f18,8;hklg,h3w,8;0,2ag,6|3l3r~0,o,k,9~ixd4,hmc,9|3n~0,j,k,9~|a8~0,s,14,a~l7s4,r40,a|9o~k,2,w,2~f60s,29eo,2|9c9d~0,a,s,b~0,8ge4,b|9q9s~~8ge4,fk0,7;9us,hmk,7|9t~~8ge4,fk0,7|9v~~3y3k,fjw,7|9w~0,4,s,7~3y3k,fjw,7|91~0,k,g,c~hx2g,5pc,c|9g~0,e,o,5~bf7o,hmk,5|9i~0,7,o,5~67ic,f18,5|9j~4,m,o,5~2g6c,f18,5;hklg,h3w,5|9k~~4dng,bes,b|9l~~4dng,bes,b;46vw,9us,b|a9~0,s,18,d~lnus,beo,d|4o~0,e,2o,e~b4s8,beo,e;0,g2s,f|4g~0,8,1w,2;a,i,1w,g~6xx4,g2o,2;0,ej0w,g|4h~0,8,1w,2;a,i,1w,g~6mic,beo,2;g2o,ej10,g|4i~0,8,1w,h;a,i,1w,g~6xx4,g2o,h;0,ej0w,g|4w~0,j,24,i~|51~0,9,20,j~7ovq,a7m,j|ap~~gelg,aw0,k|5o~0,3,28,f~0,3qcg,f|4y~g,2,24,l~bg7g,g2s,m;aw0,2oyk,l|4z~0,f,24,m;g,3,24,l~|4j~0,8,1w,h;a,i,1w,g~6xx4,g2o,h;0,ej0w,g|4k~0,9,1w,h~|4l~0,9,1w,n;n,5,1w,g~i0i0,3wio,g|5r~0,1,2k,o;3,c,2k,p;g,3,2k,o~1d8c,beo,o;0,fk4,p;duao,2ao,q|5s~j,1,2k,q~ew48,14g8,q|63~~74ng,9cg,r|50~0,j,24,i~|6c~~67w,dhc,2|6f~0,e,10,s~b17c,gl8,s|6k6m6n~0,f,1s,f;g,3,1s,t~|b5~0,0,1g,u~jpg,e00,u|6q~0,f,1o,v;g,2,1o,w~c76o,2p14,w|6l~~bg7s,g2s,p|6s~3,f,1o,v~1oo4,fk0,v|az~~2fms,fk0,0;beo,g2o,0|7c~0,4,2g,r~0,4ho8,r|7d~0,4,2g,x~0,4ho8,x';

export const abbrFixClasses = /*@__PURE__*/ decodeAbbrFix(Z, A, F, ABBRFIX_FROM, STEP_MS);
