// AUTO-GENERATED by tools/gen-abbrfix.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// Historical abbreviation corrections (1995-2025), layered over the
// offset-only history eras. history.ts stores no labels, so below the bake year
// an abbreviation is derived from the resolved OFFSET alone — which is wrong
// wherever a zone's historical identity differs from its modern schedule class
// (America/Ciudad_Juarez was Central in 1998; -360 matches its modern Mountain
// class's MDT). These carry the label live Intl reports, for the instants where
// that answer is a confident lie. Where the offset matches no modern state (so
// the fallback is a vague GMT±N rather than a wrong name) it is NOT corrected.
//
// Keyed by (year range, offset), not by timestamp: the wrong label is itself a
// function of the offset, so a record need only say "in these years this offset
// means X". 703 disagreeing spans collapse to 55 range records; the
// 73 spans that survive cover years where one offset holds two identities.
// 77 zones -> 55 shared payloads, 35 distinct labels
// (53 of the spans land in defer eras, resolved via the schedule class)
// Covers 537 zone-years that would otherwise be mislabelled.
// Consumed via shared/rules.ts resolveAbbrFix (tests/history.test.ts pins it).
// generated by: chrome-headless-shell 151.0.7922.47, 2026-07-27T22:35:42.424Z

import { decodeAbbrFix } from '../../decode.ts';
import { scheduleClasses, STEP_MS } from './schedule.ts';

export const genMeta = {
  "host": "chrome-headless-shell 151.0.7922.47",
  "icu": null,
  "generated": "2026-07-27T22:35:42.424Z"
} as const;

export const ABBRFIX_FROM = 1995;

// same zone-index space as history.ts. The eager decode is /*@__PURE__*/ so a
// bundler drops this table whenever nothing references abbrFixClasses — which
// is every schedule-only entry point, since only shared/bakedHistory.ts reads it.
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const A = 'CEST,GMT+2,AST,WAST,PYST,MDT,CST,CDT,MPDT,CLST,PDT,WGST,EST,PST,EGST,ANAT,MST,WKT,GMT+5,GMT+7,GMT+6,EET,NOVT,NST,KST,SAKT,SST,GMT+11,GST,FIST,MSK,CET,EEST,FET,NMIT';
const F = '1h~~1p18,djw,0;bmw8,fk0,0|1d~0,l,1k,1~gag4,fjw,1;bes,3ro,1|2e2f2g2h2j2k2l2m2n2o2p~~3klo,b9c,2|2i~d,0,10,3~3klo,b9c,3;6gys,avw,3|2q~0,s,10,4~llsg,cyk,4;eis,nw,4|2r~1,d,o,5~|96~5,0,o,6~3mow,beo,6;g2c,awg,6|3a~1,0,s,7;4,f,s,7~1p7k,f18,7;kqk,684,7|2t~4,m,o,8~2g6c,f18,8;hm5g,fjw,8|97~0,2,o,6;4,m,o,8~248s,bxk,6;0,f18,8;hklg,h3w,8;0,2ag,6|3h~k,0,10,9~mjpc,5sc,9|3l3r~0,o,k,a~ixd4,hmc,a|3n~0,j,k,a~|a8~0,s,14,b~lslc,6as,b|9o~k,2,w,2~f60s,29eo,2|9c9d~0,a,s,c~0,8ge4,c|9q9s~~8ge4,fk0,7;9us,hmk,7|9t~~8ge4,fk0,7|9v~~3y3k,fjw,7|9w~0,4,s,7~3y3k,fjw,7|91~0,k,g,d~hx2g,5pc,d|9g~0,e,o,5~bf7o,hmk,5|9i~0,7,o,5~67ic,f18,5|9j~4,m,o,5~2g6c,f18,5;hklg,h3w,5|3i3j~k,0,10,9~|9k~~4dng,bes,c|9l~~4dng,bes,c;46vw,9us,c|a9~0,s,18,e~lnus,beo,e|4o~0,e,2o,f~b4s8,beo,f;0,g2s,g|4g~0,8,1w,2;a,i,1w,h~6xx4,g2o,2;0,4lk,h;0,eefc,h|4h~0,8,1w,2;a,i,1w,h~6mic,beo,2;g2o,4lo,h;0,eefc,h|4i~0,8,1w,i;a,i,1w,h~6xx4,g2o,i;0,4lk,h;0,eefc,h|4w~0,j,24,j~|51~0,9,20,k~7ovq,a7m,k|ap~~gelg,aw0,l|5o~0,3,28,g~0,3qcg,g|4y~g,2,24,m~bg7g,g2s,n;vn4,247g,m|4z~0,f,24,n;g,3,24,m~|4j~0,8,1w,i;a,i,1w,h~6xx4,g2o,i;0,4lk,h;0,eefc,h|4k~0,9,1w,i~|4l~0,9,1w,o;n,5,1w,h~i1c0,3voo,h|5r~0,1,2k,p;3,c,2k,q;g,3,2k,p~1d8c,beo,p;0,fk4,q;duao,2ao,r|5s~j,1,2k,r~f140,zgg,r|63~~74ng,9cg,s|50~0,j,24,j~|6c~~67w,dhc,2|6f~0,e,10,t~b17c,gl8,t|6k6m6n~0,f,1s,g;g,3,1s,u~|b5~0,0,1g,v~jpg,e00,v|6q~0,f,1o,w;g,2,1o,x~crxc,24ag,x|6l~~bg7s,g2s,q|6s~3,f,1o,w~1oo4,fk0,w|az~~2fms,fk0,0;beo,g2o,0|7c~0,4,2g,s~0,4ho8,s|7d~0,4,2g,y~0,4ho8,y';

export const abbrFixClasses = /*@__PURE__*/ decodeAbbrFix(Z, A, F, ABBRFIX_FROM, STEP_MS);
