// Validation + benchmark summary across all implementations.
// Run: bun bench/bench.ts

import { impls } from '../impls/registry.ts';
import { fixtures } from '../shared/fixtures.ts';
import { zones } from '../shared/zones.ts';
import { genMeta } from '../shared/schedule.ts';

const ITERATIONS = 25;
const HOUR_MS = 3_600_000;
const BASE_TS = Date.UTC(2026, 5, 1, 12, 0);

// two perf loops per impl:
// - hit: timestamps stay within one hour bucket -> hour-bucket memo hits
// - miss: each iteration advances to the next hour bucket -> full recompute
const hitTimestamps = Array.from({ length: ITERATIONS }, (_, i) => BASE_TS + i * 1000);
const missTimestamps = Array.from({ length: ITERATIONS }, (_, i) => BASE_TS + (i + 1) * HOUR_MS);

interface Row {
  id: string;
  fixturesPassed: string;
  letterAbbrs: string;
  coldMs: string;
  hitMedUs: string;
  missMeanMs: string;
  missMinMs: string;
}

const rows: Row[] = [];

for (const impl of impls) {
  // --- validation ---
  let passed = 0;

  for (const f of fixtures) {
    const info = impl.getTimeZonesAt(f.ts).find((z) => z.name === f.zone);

    if (info !== undefined && info.abbr === f.abbr && info.offset === f.offset) passed++;
  }

  // letter-abbr coverage: zones whose abbr is not GMT/UT offset-styled
  const summer = impl.getTimeZonesAt(Date.UTC(2026, 6, 15));
  const letterAbbrs = summer.filter((z) => !/^(GMT|UTC?)([+-]|$)/.test(z.abbr) || z.abbr === 'GMT' || z.abbr === 'UTC').length;

  // --- benchmark ---
  // formatter caches are already warm from validation above; the true cold
  // cost is measured separately below in fresh subprocesses.
  const timeMs = (ts: number) => {
    const t0 = Bun.nanoseconds();
    impl.getTimeZonesAt(ts);
    return (Bun.nanoseconds() - t0) / 1e6;
  };

  impl.getTimeZonesAt(BASE_TS); // populate the hour-bucket memo slot
  const hitTimes = hitTimestamps.map(timeMs);

  const missTimes = missTimestamps.map(timeMs);

  const median = (xs: number[]) => xs.toSorted((a, b) => a - b)[xs.length >> 1]!;
  const mean = missTimes.reduce((a, b) => a + b, 0) / missTimes.length;

  rows.push({
    id: impl.id,
    fixturesPassed: `${passed}/${fixtures.length}`,
    letterAbbrs: `${letterAbbrs}/${zones.length}`,
    coldMs: '-',
    hitMedUs: (median(hitTimes) * 1000).toFixed(1),
    missMeanMs: mean.toFixed(3),
    missMinMs: Math.min(...missTimes).toFixed(3),
  });
}

// true cold-start cost (formatter construction) measured in fresh subprocesses
for (const row of rows) {
  const proc = Bun.spawnSync({
    cmd: [
      process.execPath,
      '-e',
      `const { impls } = await import(${JSON.stringify(new URL('../impls/registry.ts', import.meta.url).pathname)});
       const impl = impls.find((i) => i.id === ${JSON.stringify(row.id)});
       const t0 = Bun.nanoseconds();
       impl.getTimeZonesAt(${Date.UTC(2026, 6, 15)});
       console.log(((Bun.nanoseconds() - t0) / 1e6).toFixed(3));`,
    ],
  });

  row.coldMs = proc.stdout.toString().trim() || 'err';
}

console.log(`zones: ${zones.length}, iterations: ${ITERATIONS}, runtime: bun ${Bun.version}, tables: ${genMeta.host}\n`);

if (!genMeta.host.startsWith('bun')) {
  console.warn(`WARNING: active tables were generated by "${genMeta.host}" — run \`bun run tables bun\` for a fair bun benchmark\n`);
}

const headers = ['impl', 'fixtures', 'letter abbrs', 'cold ms', 'hit median µs', 'miss mean ms', 'miss min ms'];
const cells = rows.map((r) => [r.id, r.fixturesPassed, r.letterAbbrs, r.coldMs, r.hitMedUs, r.missMeanMs, r.missMinMs]);
const widths = headers.map((h, i) => Math.max(h.length, ...cells.map((c) => c[i]!.length)));

const line = (c: string[]) => c.map((v, i) => v.padEnd(widths[i]!)).join('  ');

console.log(line(headers));
console.log(widths.map((w) => '-'.repeat(w)).join('  '));
for (const c of cells) console.log(line(c));

console.log(
  '\nnotes:\n' +
    impls.map((i) => `  ${i.id}: ${i.notes}`).join('\n')
);
