// Validation + benchmark summary across all implementations.
// Run: bun bench/bench.ts

import { impls } from '../impls/registry.ts';
import { fixtures } from '../shared/fixtures.ts';
import { zones } from '../shared/zones.ts';
import { genMeta } from '../shared/schedule.ts';

const ITERATIONS = 25;
const HOUR_MS = 3_600_000;
const BASE_TS = Date.UTC(2026, 5, 1, 12, 0);

// two perf loops per impl:
// - hit: timestamps stay within one hour bucket -> hour-bucket memo hits
// - miss: each iteration advances to the next hour bucket -> full recompute
const hitTimestamps = Array.from({ length: ITERATIONS }, (_, i) => BASE_TS + i * 1000);
const missTimestamps = Array.from({ length: ITERATIONS }, (_, i) => BASE_TS + (i + 1) * HOUR_MS);

interface Row {
  id: string;
  fixturesPassed: string;
  letterAbbrs: string;
  coldMs: string;
  hitMedUs: string;
  missMedMs: string;
  formatters: string;
}

const rows: Row[] = [];

for (const impl of impls) {
  // --- benchmark first, validation after, so the heavy correctness sweep
  // can't thermally throttle the CPU under the measurements. the priming
  // call below warms this impl's formatter caches; the true cold cost is
  // measured separately in fresh subprocesses.
  const timeMs = (ts: number) => {
    const t0 = Bun.nanoseconds();
    impl.getTimeZonesAt(ts);
    return (Bun.nanoseconds() - t0) / 1e6;
  };

  // brief untimed warm-up (formatter caches + JIT + memo paths) — replaces
  // the warming the validation sweep used to provide, at ~2% of its cost
  for (let i = 0; i < 5; i++) impl.getTimeZonesAt(BASE_TS - (i + 1) * HOUR_MS);

  impl.getTimeZonesAt(BASE_TS); // populate the hour-bucket memo slot
  const hitTimes = hitTimestamps.map(timeMs);

  const missTimes = missTimestamps.map(timeMs);

  // --- validation ---
  let passed = 0;

  for (const f of fixtures) {
    const info = impl.getTimeZonesAt(f.ts).find((z) => z.name === f.zone);

    if (info !== undefined && info.abbr === f.abbr && info.offset === f.offset) passed++;
  }

  // letter-abbr coverage: zones whose abbr is not GMT/UT offset-styled
  const summer = impl.getTimeZonesAt(Date.UTC(2026, 6, 15));
  const letterAbbrs = summer.filter((z) => !/^(GMT|UTC?)([+-]|$)/.test(z.abbr) || z.abbr === 'GMT' || z.abbr === 'UTC').length;

  const median = (xs: number[]) => xs.toSorted((a, b) => a - b)[xs.length >> 1]!;

  rows.push({
    id: impl.id,
    fixturesPassed: `${passed}/${fixtures.length}`,
    letterAbbrs: `${letterAbbrs}/${zones.length}`,
    coldMs: '-',
    hitMedUs: (median(hitTimes) * 1000).toFixed(1),
    missMedMs: median(missTimes).toFixed(1),
    formatters: '-',
  });
}

// true cold-start cost (formatter construction) measured in fresh subprocesses
for (const row of rows) {
  const proc = Bun.spawnSync({
    cmd: [
      process.execPath,
      '-e',
      `const { impls } = await import(${JSON.stringify(new URL('../impls/registry.ts', import.meta.url).pathname)});
       const { formatterCount } = await import(${JSON.stringify(new URL('../shared/fmt.ts', import.meta.url).pathname)});
       const impl = impls.find((i) => i.id === ${JSON.stringify(row.id)});
       const t0 = Bun.nanoseconds();
       impl.getTimeZonesAt(${Date.UTC(2026, 6, 15)});
       console.log(JSON.stringify({ cold: +((Bun.nanoseconds() - t0) / 1e6).toFixed(1), formatters: formatterCount() }));`,
    ],
  });

  const parsed = JSON.parse(proc.stdout.toString() || '{}') as { cold?: number; formatters?: number };

  row.coldMs = parsed.cold?.toFixed(1) ?? 'err';
  row.formatters = String(parsed.formatters ?? '-');
}

console.log(`zones: ${zones.length}, iterations: ${ITERATIONS}, runtime: bun ${Bun.version}, tables: ${genMeta.host}\n`);

if (!genMeta.host.startsWith('bun')) {
  console.warn(`WARNING: active tables were generated by "${genMeta.host}" — run \`bun run tables bun\` for a fair bun benchmark\n`);
}

const table = (headers: string[], cells: string[][]) => {
  const widths = headers.map((h, i) => Math.max(h.length, ...cells.map((c) => c[i]!.length)));
  // first column (impl) left-aligned, value columns right-aligned
  const line = (c: string[]) => c.map((v, i) => (i === 0 ? v.padEnd(widths[i]!) : v.padStart(widths[i]!))).join('  ');

  console.log(line(headers));
  console.log(widths.map((w) => '-'.repeat(w)).join('  '));
  for (const c of cells) console.log(line(c));
};

console.log('performance:\n');
// hit and miss are medians over the iteration loops
table(
  ['impl', 'cold ms', 'hit µs', 'miss ms', 'formatters'],
  rows.map((r) => [r.id, r.coldMs, r.hitMedUs, r.missMedMs, r.formatters])
);

console.log('\ncorrectness:\n');
table(
  ['impl', 'fixtures', 'letter abbrs'],
  rows.map((r) => [r.id, r.fixturesPassed, r.letterAbbrs])
);

console.log(
  '\nnotes:\n' +
    impls.map((i) => `  ${i.id}: ${i.notes}`).join('\n')
);
