// formatOffset() for the live impls (04/08): renders a signed-minutes UTC
// offset (a TimeZoneInfo.offset) as an ISO-style "±HH:MM" string.
//
// It's an O(1) read from the pre-baked offset->string lookup
// (shared/tables/<variant>/offsets.ts, generated by tools/gen-offsets.ts from
// the distinct offsets across the schedule + history tables), formatting on
// the fly only for offsets outside that baked set — arbitrary caller input, or
// a live Intl offset no baked table covers. The baked strings are exactly what
// the fallback would produce, so both paths always agree.
//
// The baked impls (07/10) use offsetFormatBaked.ts instead, which drops this
// fallback (and thus the formatter) since their offsets are always in the set.

import { offsetStrings } from './offsets.ts';
import { formatOffset as buildOffset } from './fmt.ts';

export function formatOffset(minutes: number): string {
  return offsetStrings.get(minutes) ?? buildOffset(minutes);
}
