// Year-independent schedule classes and their runtime resolution.
//
// Most DST rules are "nth weekday of month at HH:MM local wall time" (US:
// second Sunday of March 02:00; EU: last Sunday of March, 02:00/03:00 wall).
// The generator fits these rules by probing three consecutive years, so the
// table stays correct across year boundaries without regeneration — only
// genuine policy changes (and the rare non-Gregorian rule, kept as
// 'irregular' with current-year segments) can stale it.
//
// Browser-safe; used by impls 07/10, the decoder, and the generator's
// self-verification (the SAME resolver is verified and shipped).

import { zoneLinks } from './zoneLinks.ts';

export interface ZoneState {
  abbr: string;
  offMin: number; // UTC offset in minutes
}

export interface Rule {
  month: number; // 1-12
  nth: number; // 1-4 = nth <dow> of month, 5 = last <dow> of month
  dow: number; // 0 = Sunday
  atMin: number; // local WALL time of the transition, minutes since midnight
  to: 0 | 1; // index into states that this transition switches TO
}

export type ScheduleClass =
  | { zones: string[]; kind: 0; states: [ZoneState] } // static all year
  | { zones: string[]; kind: 1; states: [ZoneState, ZoneState]; rules: [Rule, Rule] } // two-state cycle
  | { zones: string[]; kind: 2; starts: number[]; abbrs: string[]; offMins: number[] }; // year-specific segments

// schedule class index per zone of `zoneList`, bridging spelling variants
// (tzdata backward links) so a table generated by a runtime that enumerates
// e.g. Asia/Calcutta serves a runtime that enumerates Asia/Kolkata and vice
// versa; -1 = no entry even after bridging (genuinely new/unknown zone)
export function buildScheduleIndex(zoneList: readonly string[], classes: readonly { zones: string[] }[]): number[] {
  const idxOf = new Map<string, number>();

  for (let i = 0; i < classes.length; i++) {
    for (const z of classes[i]!.zones) idxOf.set(z, i);
  }

  return zoneList.map((z) => idxOf.get(z) ?? idxOf.get(zoneLinks.get(z) ?? '') ?? -1);
}

// UTC instant (ms) at which `rule` fires in `year`; offBeforeMin converts
// the local wall time to UTC (the offset in effect BEFORE the transition)
export function ruleInstant(year: number, rule: Rule, offBeforeMin: number): number {
  let day: number;

  if (rule.nth === 5) {
    // last <dow> of month
    const daysInMonth = new Date(Date.UTC(year, rule.month, 0)).getUTCDate();
    const lastDow = new Date(Date.UTC(year, rule.month - 1, daysInMonth)).getUTCDay();
    day = daysInMonth - ((lastDow - rule.dow + 7) % 7);
  } else {
    const firstDow = new Date(Date.UTC(year, rule.month - 1, 1)).getUTCDay();
    day = 1 + ((rule.dow - firstDow + 7) % 7) + (rule.nth - 1) * 7;
  }

  return Date.UTC(year, rule.month - 1, day) + (rule.atMin - offBeforeMin) * 60_000;
}

// ---- shared resolution primitives (used by both the schedule resolver and
// the historical era resolver below, which are otherwise identical in their
// rule/segment handling — only their return shape differs) ----

// index (0|1) of the state/offset active at `ts` for a two-rule DST cycle
// over the two offsets [off0, off1]. Rules are month-sorted; `r.to` indexes
// the pair, and the offset in effect BEFORE a transition is the "from" side
// (1 - r.to). Scalar offsets (not an array) keep this allocation-free on the
// hot path. Before the year's first transition the active state is whatever
// the LAST transition of the (identical) previous year switched to.
function ruleCycleIndex(off0: number, off1: number, r1: Rule, r2: Rule, year: number, ts: number): 0 | 1 {
  const t1 = ruleInstant(year, r1, r1.to === 0 ? off1 : off0);
  const t2 = ruleInstant(year, r2, r2.to === 0 ? off1 : off0);

  if (ts < t1) return r2.to;
  if (ts < t2) return r1.to;
  return r2.to;
}

// index of the ascending 15-min-step segment active at `ts`, measured from
// `anchor` (Jan 1 of the relevant year). Shared by schedule irregular
// segments and historical raw-year segments.
function segmentIndex(starts: readonly number[], ts: number, anchor: number, stepMs: number): number {
  const step = Math.max(0, Math.floor((ts - anchor) / stepMs));
  let i = starts.length - 1;

  while (i > 0 && starts[i]! > step) i--;

  return i;
}

// state of a class at `ts`. yearStart/stepMs anchor the irregular segments
// (which are only valid for the generated year and clamp outside it).
export function resolveClass(cls: ScheduleClass, ts: number, yearStart: number, stepMs: number): ZoneState {
  if (cls.kind === 0) return cls.states[0];

  if (cls.kind === 1) {
    const [r1, r2] = cls.rules; // emitted sorted by month
    const year = new Date(ts).getUTCFullYear();

    return cls.states[ruleCycleIndex(cls.states[0].offMin, cls.states[1].offMin, r1, r2, year, ts)];
  }

  const i = segmentIndex(cls.starts, ts, yearStart, stepMs);

  return { abbr: cls.abbrs[i]!, offMin: cls.offMins[i]! };
}

// ---- historical eras (sidecar tables/<variant>/history.ts) ----
//
// Offsets-only history for years BEFORE the bake year, as a sequence of
// eras per zone group. An era starts at Jan 1 of fromYear and runs until
// the next era (or the bake year, where the main schedule takes over):
//   kind 0: static offset for the whole span
//   kind 1: two-offset cycle driven by two nth-weekday rules (same Rule
//           shape and per-year resolution as schedule kind 1)
//   kind 2: raw single year — explicit 15-min-step segments; used for
//           mid-year regime changes and years that fit no Gregorian rule
//   kind 3: defer — the zone's SCHEDULE class reproduces these years
//           exactly (transition-instant level), so nothing is stored and
//           resolveHistory returns null; the caller resolves via the
//           schedule. Zones whose whole history matches the schedule have
//           no history class at all.
// Abbreviations are intentionally not stored: historical labels would be
// formatted with TODAY's CLDR names anyway, and offsets are what
// historical coverage means.

export interface HistoryEra {
  fromYear: number;
  kind: 0 | 1 | 2 | 3;
  offs: number[]; // kind 0: [off]; kind 1: [offA, offB]; kind 2: per segment
  rules: [Rule, Rule] | null; // kind 1 only; sorted by month; to indexes offs
  steps: number[] | null; // kind 2 only; 15-min steps since Jan 1 of fromYear
}

export interface HistoryClass {
  zones: string[];
  eras: HistoryEra[]; // ordered by fromYear
}

// offset (minutes) of `eras` at `ts`, or null when the era defers to the
// zone's schedule class (kind 3); clamps to the first/last era outside the
// covered span (callers gate on [HISTORY_FROM, bake year) themselves)
export function resolveHistory(eras: HistoryEra[], ts: number, stepMs: number): number | null {
  const year = new Date(ts).getUTCFullYear();
  let e = eras[0]!;

  for (const era of eras) {
    if (era.fromYear <= year) e = era;
    else break;
  }

  if (e.kind === 3) return null; // schedule class covers this span

  if (e.kind === 0) return e.offs[0]!;

  if (e.kind === 1) {
    const [r1, r2] = e.rules!;

    return e.offs[ruleCycleIndex(e.offs[0]!, e.offs[1]!, r1, r2, year, ts)]!;
  }

  // raw single year, anchored at its own Jan 1
  return e.offs[segmentIndex(e.steps!, ts, Date.UTC(e.fromYear, 0, 1), stepMs)]!;
}
