// Year-independent schedule classes and their runtime resolution.
//
// Most DST rules are "nth weekday of month at HH:MM local wall time" (US:
// second Sunday of March 02:00; EU: last Sunday of March, 02:00/03:00 wall).
// The generator fits these rules by probing three consecutive years, so the
// table stays correct across year boundaries without regeneration — only
// genuine policy changes (and the rare non-Gregorian rule, kept as
// 'irregular' with current-year segments) can stale it.
//
// Browser-safe; used by impls 07/09, the decoder, and the generator's
// self-verification (the SAME resolver is verified and shipped).

import { zoneLinks } from './zoneLinks.ts';

export interface ZoneState {
  abbr: string;
  offMin: number; // UTC offset in minutes
}

export interface Rule {
  month: number; // 1-12
  nth: number; // 1-4 = nth <dow> of month, 5 = last <dow> of month
  dow: number; // 0 = Sunday
  atMin: number; // local WALL time of the transition, minutes since midnight
  to: 0 | 1; // index into states that this transition switches TO
}

export type ScheduleClass =
  | { zones: string[]; kind: 0; states: [ZoneState] } // static all year
  | { zones: string[]; kind: 1; states: [ZoneState, ZoneState]; rules: [Rule, Rule] } // two-state cycle
  | { zones: string[]; kind: 2; starts: number[]; abbrs: string[]; offMins: number[] }; // year-specific segments

// schedule class index per zone of `zoneList`, bridging spelling variants
// (tzdata backward links) so a table generated by a runtime that enumerates
// e.g. Asia/Calcutta serves a runtime that enumerates Asia/Kolkata and vice
// versa; -1 = no entry even after bridging (genuinely new/unknown zone)
export function buildScheduleIndex(zoneList: readonly string[], classes: ScheduleClass[]): number[] {
  const idxOf = new Map<string, number>();

  for (let i = 0; i < classes.length; i++) {
    for (const z of classes[i]!.zones) idxOf.set(z, i);
  }

  return zoneList.map((z) => idxOf.get(z) ?? idxOf.get(zoneLinks.get(z) ?? '') ?? -1);
}

// UTC instant (ms) at which `rule` fires in `year`; offBeforeMin converts
// the local wall time to UTC (the offset in effect BEFORE the transition)
export function ruleInstant(year: number, rule: Rule, offBeforeMin: number): number {
  let day: number;

  if (rule.nth === 5) {
    // last <dow> of month
    const daysInMonth = new Date(Date.UTC(year, rule.month, 0)).getUTCDate();
    const lastDow = new Date(Date.UTC(year, rule.month - 1, daysInMonth)).getUTCDay();
    day = daysInMonth - ((lastDow - rule.dow + 7) % 7);
  } else {
    const firstDow = new Date(Date.UTC(year, rule.month - 1, 1)).getUTCDay();
    day = 1 + ((rule.dow - firstDow + 7) % 7) + (rule.nth - 1) * 7;
  }

  return Date.UTC(year, rule.month - 1, day) + (rule.atMin - offBeforeMin) * 60_000;
}

// state of a class at `ts`. yearStart/stepMs anchor the irregular segments
// (which are only valid for the generated year and clamp outside it).
export function resolveClass(cls: ScheduleClass, ts: number, yearStart: number, stepMs: number): ZoneState {
  if (cls.kind === 0) return cls.states[0];

  if (cls.kind === 1) {
    const year = new Date(ts).getUTCFullYear();
    const [r1, r2] = cls.rules; // emitted sorted by month
    const t1 = ruleInstant(year, r1, cls.states[1 - r1.to]!.offMin);
    const t2 = ruleInstant(year, r2, cls.states[1 - r2.to]!.offMin);

    // before the year's first transition, the state is whatever the LAST
    // transition of the (identical) previous year switched to
    if (ts < t1) return cls.states[r2.to];
    if (ts < t2) return cls.states[r1.to];
    return cls.states[r2.to];
  }

  const step = Math.max(0, Math.floor((ts - yearStart) / stepMs));
  let i = cls.starts.length - 1;

  while (i > 0 && cls.starts[i]! > step) i--;

  return { abbr: cls.abbrs[i]!, offMin: cls.offMins[i]! };
}
