// Year-independent schedule classes and their runtime resolution.
//
// Most DST rules are "nth weekday of month at HH:MM local wall time" (US:
// second Sunday of March 02:00; EU: last Sunday of March, 02:00/03:00 wall).
// The generator fits these rules by probing three consecutive years, so the
// table stays correct across year boundaries without regeneration — only
// genuine policy changes (and the rare non-Gregorian rule, kept as
// 'irregular' with current-year segments) can stale it.
//
// Browser-safe; used by impls 07/10, the decoder, and the generator's
// self-verification (the SAME resolver is verified and shipped).

import { zoneLinks } from './zoneLinks.ts';
import { gmtLabel } from './fmt.ts';

export interface ZoneState {
  abbr: string;
  offMin: number; // UTC offset in minutes
}

export interface Rule {
  month: number; // 1-12
  nth: number; // 1-4 = nth <dow> of month, 5 = last <dow> of month
  dow: number; // 0 = Sunday
  atMin: number; // local WALL time of the transition, minutes since midnight
  to: 0 | 1; // index into states that this transition switches TO
}

export type ScheduleClass =
  | { zones: string[]; kind: 0; states: [ZoneState] } // static all year
  | { zones: string[]; kind: 1; states: [ZoneState, ZoneState]; rules: [Rule, Rule] } // two-state cycle
  | { zones: string[]; kind: 2; starts: number[]; abbrs: string[]; offMins: number[] }; // year-specific segments

// schedule class index per zone of `zoneList`, bridging spelling variants
// (tzdata backward links) so a table generated by a runtime that enumerates
// e.g. Asia/Calcutta serves a runtime that enumerates Asia/Kolkata and vice
// versa; -1 = no entry even after bridging (genuinely new/unknown zone)
export function buildScheduleIndex(zoneList: readonly string[], classes: readonly { zones: string[] }[]): number[] {
  const idxOf = new Map<string, number>();

  for (let i = 0; i < classes.length; i++) {
    for (const z of classes[i]!.zones) idxOf.set(z, i);
  }

  return zoneList.map((z) => idxOf.get(z) ?? idxOf.get(zoneLinks.get(z) ?? '') ?? -1);
}

// ---- allocation-free civil-date math (Howard Hinnant's algorithms) ----
//
// The rule/era resolvers run in tight per-zone loops (hundreds of classes per
// getTimeZonesAt(), and one per call for getTimeZoneAt() sweeping thousands of
// timestamps). Going through `new Date(...)` just to read a year, weekday, or
// month length allocated a throwaway Date object each time; these do the same
// arithmetic on epoch integers with zero allocation. Range-general (valid for
// any Gregorian year), so pre-1970 history is fine too.

const DAY_MS = 86_400_000;
const MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

const isLeap = (y: number): boolean => (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;

// days in month `m` (1-12) of `y`
const daysInMonth = (y: number, m: number): number => (m === 2 && isLeap(y) ? 29 : MONTH_DAYS[m - 1]!);

// days since 1970-01-01 (UTC) for the given civil date (m: 1-12)
function daysFromCivil(y: number, m: number, d: number): number {
  const yy = y - (m <= 2 ? 1 : 0);
  const era = Math.floor((yy >= 0 ? yy : yy - 399) / 400);
  const yoe = yy - era * 400;
  const doy = Math.floor((153 * (m > 2 ? m - 3 : m + 9) + 2) / 5) + d - 1;
  const doe = yoe * 365 + Math.floor(yoe / 4) - Math.floor(yoe / 100) + doy;

  return era * 146097 + doe - 719468;
}

// day of week (0 = Sunday) of a civil date; 1970-01-01 (day 0) was a Thursday
const dowFromCivil = (y: number, m: number, d: number): number => ((daysFromCivil(y, m, d) + 4) % 7 + 7) % 7;

// UTC year containing epoch-ms `ts`, with no Date allocation
export function yearFromMs(ts: number): number {
  let z = Math.floor(ts / DAY_MS) + 719468;
  const era = Math.floor((z >= 0 ? z : z - 146096) / 146097);
  const doe = z - era * 146097;
  const yoe = Math.floor((doe - Math.floor(doe / 1460) + Math.floor(doe / 36524) - Math.floor(doe / 146096)) / 365);
  const y = yoe + era * 400;
  const doy = doe - (365 * yoe + Math.floor(yoe / 4) - Math.floor(yoe / 100));
  const mp = Math.floor((5 * doy + 2) / 153);

  return (mp < 10 ? mp + 3 : mp - 9) <= 2 ? y + 1 : y;
}

// UTC instant (ms) at which `rule` fires in `year`; offBeforeMin converts
// the local wall time to UTC (the offset in effect BEFORE the transition)
export function ruleInstant(year: number, rule: Rule, offBeforeMin: number): number {
  let day: number;

  if (rule.nth === 5) {
    // last <dow> of month
    const dim = daysInMonth(year, rule.month);
    const lastDow = dowFromCivil(year, rule.month, dim);
    day = dim - ((lastDow - rule.dow + 7) % 7);
  } else {
    const firstDow = dowFromCivil(year, rule.month, 1);
    day = 1 + ((rule.dow - firstDow + 7) % 7) + (rule.nth - 1) * 7;
  }

  return daysFromCivil(year, rule.month, day) * DAY_MS + (rule.atMin - offBeforeMin) * 60_000;
}

// ---- shared resolution primitives (used by both the schedule resolver and
// the historical era resolver below, which are otherwise identical in their
// rule/segment handling — only their return shape differs) ----

// index (0|1) of the state/offset active at `ts` for a two-rule DST cycle
// over the two offsets [off0, off1]. Rules are month-sorted; `r.to` indexes
// the pair, and the offset in effect BEFORE a transition is the "from" side
// (1 - r.to). Scalar offsets (not an array) keep this allocation-free on the
// hot path. Before the year's first transition the active state is whatever
// the LAST transition of the (identical) previous year switched to.
function ruleCycleIndex(off0: number, off1: number, r1: Rule, r2: Rule, year: number, ts: number): 0 | 1 {
  const t1 = ruleInstant(year, r1, r1.to === 0 ? off1 : off0);
  const t2 = ruleInstant(year, r2, r2.to === 0 ? off1 : off0);

  if (ts < t1) return r2.to;
  if (ts < t2) return r1.to;
  return r2.to;
}

// index of the ascending 15-min-step segment active at `ts`, measured from
// `anchor` (Jan 1 of the relevant year). Shared by schedule irregular
// segments and historical raw-year segments.
function segmentIndex(starts: readonly number[], ts: number, anchor: number, stepMs: number): number {
  const step = Math.max(0, Math.floor((ts - anchor) / stepMs));
  let i = starts.length - 1;

  while (i > 0 && starts[i]! > step) i--;

  return i;
}

// Per-class derived state, memoized on the decoded class object. Both caches
// memoize pure functions of the class, so they cannot go stale: the tables are
// decoded once at module load and never mutated.
//
// kind 1: the year's two transition instants. Recomputing them per call meant
// two ruleInstant() -> daysFromCivil() runs (several divisions each) for every
// resolution, even though an all-zones response shares one instant and a
// single-zone sweep hammers one year at a time. Single-slot per class keyed by
// year, which fits both shapes; alternating years just recomputes.
//
// kind 2: the segment states. These were rebuilt fresh on every call, which
// allocated on the hot path and left the result impossible to key on by
// identity — interning them is what lets shared/bakedSchedule.ts cache
// TimeZoneInfo per (zone, state).
const transOf = new WeakMap<ScheduleClass, { year: number; t1: number; t2: number }>();
const segStatesOf = new WeakMap<ScheduleClass, ZoneState[]>();

// state of a class at `ts`. yearStart/stepMs anchor the irregular segments
// (which are only valid for the generated year and clamp outside it).
// The returned object is OWNED by the class and shared across calls — callers
// must treat it as immutable (shared/bakedSchedule.ts keys a cache on it).
export function resolveClass(cls: ScheduleClass, ts: number, yearStart: number, stepMs: number): ZoneState {
  if (cls.kind === 0) return cls.states[0];

  if (cls.kind === 1) {
    const [r1, r2] = cls.rules; // emitted sorted by month
    const year = yearFromMs(ts);

    let tc = transOf.get(cls);

    if (tc == null) transOf.set(cls, (tc = { year: NaN, t1: 0, t2: 0 })); // NaN never equals, so the first call misses

    if (tc.year !== year) {
      const off0 = cls.states[0].offMin;
      const off1 = cls.states[1].offMin;

      tc.year = year;
      tc.t1 = ruleInstant(year, r1, r1.to === 0 ? off1 : off0);
      tc.t2 = ruleInstant(year, r2, r2.to === 0 ? off1 : off0);
    }

    // same selection as ruleCycleIndex(), against the cached instants
    return cls.states[ts < tc.t1 ? r2.to : ts < tc.t2 ? r1.to : r2.to];
  }

  let segStates = segStatesOf.get(cls);

  if (segStates == null) {
    segStatesOf.set(cls, (segStates = cls.abbrs.map((abbr, s) => ({ abbr, offMin: cls.offMins[s]! }))));
  }

  return segStates[segmentIndex(cls.starts, ts, yearStart, stepMs)]!;
}

// ---- historical eras (sidecar tables/<variant>/history.ts) ----
//
// Offsets-only history for years BEFORE the bake year, as a sequence of
// eras per zone group. An era starts at Jan 1 of fromYear and runs until
// the next era (or the bake year, where the main schedule takes over):
//   kind 0: static offset for the whole span
//   kind 1: two-offset cycle driven by two nth-weekday rules (same Rule
//           shape and per-year resolution as schedule kind 1)
//   kind 2: raw single year — explicit 15-min-step segments; used for
//           mid-year regime changes and years that fit no Gregorian rule
//   kind 3: defer — the zone's SCHEDULE class reproduces these years
//           exactly (transition-instant level), so nothing is stored and
//           resolveHistory returns null; the caller resolves via the
//           schedule. Zones whose whole history matches the schedule have
//           no history class at all.
// Abbreviations are intentionally not stored: historical labels would be
// formatted with TODAY's CLDR names anyway, and offsets are what
// historical coverage means.

export interface HistoryEra {
  fromYear: number;
  kind: 0 | 1 | 2 | 3;
  offs: number[]; // kind 0: [off]; kind 1: [offA, offB]; kind 2: per segment
  rules: [Rule, Rule] | null; // kind 1 only; sorted by month; to indexes offs
  steps: number[] | null; // kind 2 only; 15-min steps since Jan 1 of fromYear
}

export interface HistoryClass {
  zones: string[];
  eras: HistoryEra[]; // ordered by fromYear
}

// offset (minutes) of `eras` at `ts`, or null when the era defers to the
// zone's schedule class (kind 3); clamps to the first/last era outside the
// covered span (callers gate on [HISTORY_FROM, bake year) themselves)
export function resolveHistory(eras: HistoryEra[], ts: number, stepMs: number): number | null {
  const year = yearFromMs(ts);
  let e = eras[0]!;

  for (const era of eras) {
    if (era.fromYear <= year) e = era;
    else break;
  }

  if (e.kind === 3) return null; // schedule class covers this span

  if (e.kind === 0) return e.offs[0]!;

  if (e.kind === 1) {
    const [r1, r2] = e.rules!;

    return e.offs[ruleCycleIndex(e.offs[0]!, e.offs[1]!, r1, r2, year, ts)]!;
  }

  // raw single year, anchored at its own Jan 1
  return e.offs[segmentIndex(e.steps!, ts, Date.UTC(e.fromYear, 0, 1), stepMs)]!;
}

// label for an offset given a schedule class: the class's abbr for that offset
// when it has one, else a generic GMT label. History-independent (reads only
// the class it is handed), so the historical labelers share it.
//
// Deliberately kept here rather than beside the baked resolvers: the generator
// (tools/abbrfix-core.ts) needs it too, and importing it from a table module
// would compile a previous generation's tables into the generator's own bundle.
export function historyAbbr(cls: ScheduleClass, offMin: number): string {
  if (cls.kind === 0) {
    if (cls.states[0].offMin === offMin) return cls.states[0].abbr;
  } else if (cls.kind === 1) {
    for (const st of cls.states) if (st.offMin === offMin) return st.abbr;
  } else {
    for (let i = 0; i < cls.offMins.length; i++) if (cls.offMins[i] === offMin) return cls.abbrs[i]!;
  }

  return gmtLabel(offMin);
}

// Historical LABEL corrections, layered over the offsets above.
//
// The eras store offsets only, so below the bake year an abbreviation is a pure
// function of the resolved offset (historyAbbr above) — one label per
// run of constant offset. That is wrong wherever a zone's historical identity
// differs from the one its modern schedule class describes: America/Ciudad_Juarez
// was on Central in 1998, but -360 matches its modern Mountain class's MDT state,
// so MDT came back with full confidence. These spans carry the label live Intl
// reports, for the instants where the offset-keyed answer is a confident lie.
//
// Sparse by construction: only the disagreeing zones are stored (68 of 464), and
// zones with identical correction lists share one payload.
//
// Keyed by (year range, offset) rather than by timestamp. The wrong label is
// itself a pure function of the resolved offset, so a correction only needs to
// say "in these years, this offset means X" — America/Cancun's 17 near-identical
// summer spans collapse to one record. `spanFrom/spanTo` carry the handful of
// years where one offset holds two identities and no range can describe it.
// Generated by tools/gen-abbrfix.ts, which audits the COMMITTED tables against
// live Intl and verifies both forms answer identically.
export interface AbbrFixClass {
  zones: string[];
  fromYear: number[]; // range starts
  toYear: number[]; // range ends, INCLUSIVE
  offs: number[]; // the offset (minutes) the range keys on
  abbrs: string[]; // the correct label for that (range, offset)
  spanFrom: number[]; // fallback spans, epoch ms, ascending
  spanTo: number[]; // exclusive
  spanAbbrs: string[];
}

// the corrected abbreviation for a zone already known to have corrections, or
// null when this instant needs none. `offMin` must be the offset the caller is
// about to label with — the historical era's where one is live, else the
// schedule class's — since that is the offset the generator keyed on.
//
// Both loops are linear: after collapsing, a class holds 1-3 ranges and usually
// no spans at all, so a binary search would cost more than it saves.
export function resolveAbbrFix(c: AbbrFixClass, ts: number, year: number, offMin: number): string | null {
  const sf = c.spanFrom;

  // spans describe the years the ranges deliberately skip, so they win
  for (let i = 0; i < sf.length; i++) {
    if (ts >= sf[i]! && ts < c.spanTo[i]!) return c.spanAbbrs[i]!;
  }

  const fy = c.fromYear;

  for (let i = 0; i < fy.length; i++) {
    if (year >= fy[i]! && year <= c.toYear[i]! && c.offs[i] === offMin) return c.abbrs[i]!;
  }

  return null;
}
