import type { TimeZoneInfo } from './types.ts';

// curation-reviewed: 2026-07-13 | IANA NEWS through tzdata 2026c | zone-list
// diff: bun 1.4 (ICU 75.1) vs chrome-headless-shell 150.0.7871.115
// Maintained by hand — see .cursor/skills/maintain-curated-tz-data/SKILL.md
//
// Canonicalization bridge for IANA zone spelling variants (tzdata backward
// links). Different ICU builds enumerate different canonical names for the
// same zone — e.g. Chrome 150 lists Asia/Calcutta and Europe/Kiev where bun
// (and modern tzdata) list Asia/Kolkata and Europe/Kyiv. Impl 09 uses this
// to look up a runtime zone name in a table generated by a runtime that
// enumerates the other spelling. Both directions are resolvable.
//
// Pairs cover every modern/legacy divergence observed between bun 1.4
// (ICU 75) and Chrome 150 zone lists, i.e. the relevant tzdata backward
// links; ~0.5KB. Zones with no counterpart (new zones like America/Coyhaique,
// or Etc/* which some browsers omit) fall back to live formatting instead.

export const zoneLinkPairs: [canonical: string, alias: string][] = [
  ['Africa/Asmara', 'Africa/Asmera'],
  ['America/Argentina/Buenos_Aires', 'America/Buenos_Aires'],
  ['America/Argentina/Catamarca', 'America/Catamarca'],
  ['America/Argentina/Cordoba', 'America/Cordoba'],
  ['America/Argentina/Jujuy', 'America/Jujuy'],
  ['America/Argentina/Mendoza', 'America/Mendoza'],
  ['America/Atikokan', 'America/Coral_Harbour'],
  ['America/Indiana/Indianapolis', 'America/Indianapolis'],
  ['America/Kentucky/Louisville', 'America/Louisville'],
  ['America/Nuuk', 'America/Godthab'],
  ['Asia/Ho_Chi_Minh', 'Asia/Saigon'],
  ['Asia/Kathmandu', 'Asia/Katmandu'],
  ['Asia/Kolkata', 'Asia/Calcutta'],
  ['Asia/Ulaanbaatar', 'Asia/Choibalsan'], // Choibalsan became a link in tzdata 2024a
  ['Asia/Yangon', 'Asia/Rangoon'],
  ['Atlantic/Faroe', 'Atlantic/Faeroe'],
  ['Europe/Kyiv', 'Europe/Kiev'],
  ['Pacific/Chuuk', 'Pacific/Truk'],
  ['Pacific/Kanton', 'Pacific/Enderbury'],
  ['Pacific/Pohnpei', 'Pacific/Ponape'],
];

// name -> counterpart name (both directions), for table lookups (impl 09)
export const zoneLinks = new Map<string, string>();

// legacy/alias name -> modern canonical, for TimeZoneInfo.aliasOf
export const aliasOfZone = new Map<string, string>();

for (const [canonical, alias] of zoneLinkPairs) {
  zoneLinks.set(canonical, alias);
  zoneLinks.set(alias, canonical);
  aliasOfZone.set(alias, canonical);
}

// single construction point for TimeZoneInfo so every impl attaches aliasOf
// identically (the cross-impl equivalence tests depend on this)
export function makeInfo(name: string, abbr: string, offset: string): TimeZoneInfo {
  const aliasOf = aliasOfZone.get(name);

  return aliasOf === undefined ? { name, abbr, offset } : { name, abbr, offset, aliasOf };
}
