import type { TimeZoneInfo } from './types.ts';

// curation-reviewed: 2026-07-16 | IANA NEWS through tzdata 2026c | zone-list
// diff: bun 1.4 (ICU 75.1) vs chrome-headless-shell 151.0.7922.34 (418
// zones, unchanged from 150 — no new spelling divergences)
// Maintained by hand — see .cursor/skills/maintain-curated-tz-data/SKILL.md
//
// Canonicalization bridge for IANA zone spelling variants (tzdata backward
// links). Different ICU builds enumerate different canonical names for the
// same zone — e.g. Chrome 150 lists Asia/Calcutta and Europe/Kiev where bun
// (and modern tzdata) list Asia/Kolkata and Europe/Kyiv. Impl 09 uses this
// to look up a runtime zone name in a table generated by a runtime that
// enumerates the other spelling. Both directions are resolvable.
//
// Pairs cover every modern/legacy divergence observed between bun 1.4
// (ICU 75) and Chrome 150 zone lists, i.e. the relevant tzdata backward
// links; ~0.5KB. Zones with no counterpart (new zones like America/Coyhaique,
// or Etc/* which some browsers omit) fall back to live formatting instead.

export const zoneLinkPairs: [canonical: string, alias: string][] = [
  ['Africa/Asmara', 'Africa/Asmera'],
  ['America/Argentina/Buenos_Aires', 'America/Buenos_Aires'],
  ['America/Argentina/Catamarca', 'America/Catamarca'],
  ['America/Argentina/Cordoba', 'America/Cordoba'],
  ['America/Argentina/Jujuy', 'America/Jujuy'],
  ['America/Argentina/Mendoza', 'America/Mendoza'],
  ['America/Atikokan', 'America/Coral_Harbour'],
  ['America/Indiana/Indianapolis', 'America/Indianapolis'],
  ['America/Kentucky/Louisville', 'America/Louisville'],
  ['America/Nuuk', 'America/Godthab'],
  ['Asia/Ho_Chi_Minh', 'Asia/Saigon'],
  ['Asia/Kathmandu', 'Asia/Katmandu'],
  ['Asia/Kolkata', 'Asia/Calcutta'],
  ['Asia/Ulaanbaatar', 'Asia/Choibalsan'], // Choibalsan became a link in tzdata 2024a
  ['Asia/Yangon', 'Asia/Rangoon'],
  ['Atlantic/Faroe', 'Atlantic/Faeroe'],
  ['Europe/Kyiv', 'Europe/Kiev'],
  ['Pacific/Chuuk', 'Pacific/Truk'],
  ['Pacific/Kanton', 'Pacific/Enderbury'],
  ['Pacific/Pohnpei', 'Pacific/Ponape'],
];

// name -> counterpart name (both directions), for table lookups (impl 09)
export const zoneLinks = new Map<string, string>();

// legacy/alias name -> modern canonical, for TimeZoneInfo.aliasOf
export const aliasOfZone = new Map<string, string>();

for (const [canonical, alias] of zoneLinkPairs) {
  zoneLinks.set(canonical, alias);
  zoneLinks.set(alias, canonical);
  aliasOfZone.set(alias, canonical);
}

// Interned, frozen TimeZoneInfo pool. The set of distinct (name, abbr, offset)
// triples a zone can produce is small and finite — its standard/DST states, a
// handful of irregular-year segments, and the historical offset labels — so
// across the ~450 zones there are on the order of ~10^3 possible results in
// total. We build each lazily on first sighting and return that same frozen
// instance on every later call, turning the per-call allocation (hundreds per
// getTimeZonesAt(), one per getTimeZoneAt()) into a pointer lookup that
// produces no garbage. Freezing guarantees a caller can't mutate a shared
// instance and corrupt another call's result.
//
// Nested maps (name -> offset-minutes -> abbr) key the pool directly on the
// numeric offset — no string built on the hot path. The pool is
// process-lifetime and bounded by the finite result space, so it never needs
// eviction.
const internPool = new Map<string, Map<number, Map<string, Readonly<TimeZoneInfo>>>>();

// getTimeZonesAt() only ever asks for the fixed zone list, but getTimeZoneAt()
// takes a caller-supplied name and answers a UTC sentinel for unknown ones —
// so the pool's outer key is untrusted input. Cap the number of distinct names
// well above every real IANA spelling (~900); past it, results are still built
// and frozen, just not retained, so a flood of junk names can't grow the pool
// without bound. Real zones are always pooled.
const POOL_NAME_CAP = 4096;

function freezeInfo(name: string, abbr: string, offset: number): Readonly<TimeZoneInfo> {
  const aliasOf = aliasOfZone.get(name);

  return Object.freeze(aliasOf == null ? { name, abbr, offset } : { name, abbr, offset, aliasOf });
}

// single construction point for TimeZoneInfo so every impl attaches aliasOf
// identically (the cross-impl equivalence tests depend on this) and shares the
// interned, frozen pool above. `offset` is signed minutes (see TimeZoneInfo).
export function makeInfo(name: string, abbr: string, offset: number): TimeZoneInfo {
  let byOffset = internPool.get(name);

  if (byOffset == null) {
    if (internPool.size >= POOL_NAME_CAP) return freezeInfo(name, abbr, offset);

    internPool.set(name, (byOffset = new Map()));
  }

  let byAbbr = byOffset.get(offset);

  if (byAbbr == null) byOffset.set(offset, (byAbbr = new Map()));

  let info = byAbbr.get(abbr);

  if (info == null) byAbbr.set(abbr, (info = freezeInfo(name, abbr, offset)));

  return info;
}
