// Renders generated tables into shared/tables/<variant>/{classes,schedule,
// offsets}.ts source text, in the packed format decoded by shared/decode.ts.
// Shared by the bun path (tools/gen-classes.ts) and the Chrome path
// (tools/gen-chrome.ts) so both emit byte-comparable files.
//
// Packing (minified-bundle-size motivated; see shared/decode.ts):
// - zone names: prefix dictionary ("America/Argentina/" etc.), each zone
//   encoded as one base36 prefix-index char + leaf
// - classes/lists: single delimited strings instead of array literals
// - abbrs: dictionary + base36 indices
// - offsets: signed minutes instead of "+05:30" strings, in their own file
//   so live-offset consumers (impl 09) don't bundle them

import type { GeneratedTables } from './gen-core.ts';

// provenance of the Intl data the tables were probed from; the equivalence
// tests skip when the executing runtime doesn't match
export interface GenMeta {
  host: string; // e.g. "bun 1.4.0" or "chrome-headless-shell 150.0.7871.115"
  icu: string | null; // process.versions.icu when known
  generated: string; // ISO timestamp
}

const metaExport = (meta: GenMeta) =>
  `export const genMeta = ${JSON.stringify(meta, null, 2)} as const;\n`;

const genHeader = (meta: GenMeta, what: string) =>
  `// AUTO-GENERATED by tools/gen-core.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen / bun run gen:chrome) when
// tzdata/CLDR changes or the year rolls over.
//
// ${what}
// generated by: ${meta.host}, ${meta.generated}
`;

interface ZoneCodec {
  prefixesPacked: string;
  encode: (zone: string) => string;
}

function zoneCodec(allZones: string[]): ZoneCodec {
  const counts = new Map<string, number>();

  for (const z of allZones) {
    const cut = z.lastIndexOf('/');
    const prefix = cut === -1 ? '' : z.slice(0, cut + 1);
    counts.set(prefix, (counts.get(prefix) ?? 0) + 1);
  }

  const prefixes = [...counts.keys()].sort((a, b) => counts.get(b)! - counts.get(a)!);

  if (prefixes.length > 36) throw new Error(`zone prefix dictionary overflow: ${prefixes.length} > 36`);

  const idx = new Map(prefixes.map((p, i) => [p, i]));

  return {
    prefixesPacked: prefixes.join('|'),
    encode: (zone) => {
      const cut = zone.lastIndexOf('/');
      const prefix = cut === -1 ? '' : zone.slice(0, cut + 1);
      return idx.get(prefix)!.toString(36) + zone.slice(cut + 1);
    },
  };
}

export function emitClassesTs(t: GeneratedTables, meta: GenMeta): string {
  const singletons = t.stats.sigClasses - t.stats.groups;
  const codec = zoneCodec(t.classGroups.flat());
  const groupsPacked = t.classGroups.map((g) => g.map(codec.encode).join(';')).join('|');

  const what = `Zones within a group have identical (CLDR long name, UTC offset) behavior
// at every instant of ${t.year} (15-min transition resolution). The first
// member of each group is the representative whose formatter serves all.
// ${t.stats.zones} zones -> ${t.stats.sigClasses} classes (${t.stats.groups} groups covering ${t.stats.grouped} zones + ${singletons} singletons)`;

  return `${genHeader(meta, what)}
import { decodeGroups } from '../../decode.ts';

${metaExport(meta)}
const P = '${codec.prefixesPacked}';
const G = '${groupsPacked}';

export const classGroups: string[][] = decodeGroups(P, G);
`;
}

export function emitScheduleTs(t: GeneratedTables, meta: GenMeta): string {
  const codec = zoneCodec(t.scheduleClasses.flatMap((c) => c.zones));

  const abbrDict: string[] = [];
  const abbrIdx = new Map<string, number>();

  for (const c of t.scheduleClasses) {
    for (const a of c.abbrs) {
      if (!abbrIdx.has(a)) {
        abbrIdx.set(a, abbrDict.length);
        abbrDict.push(a);
      }
    }
  }

  const zonesPacked = t.scheduleClasses.map((c) => c.zones.map(codec.encode).join(';')).join('|');
  const startsPacked = t.scheduleClasses.map((c) => c.starts.join(',')).join('|');
  const abbrsPacked = t.scheduleClasses.map((c) => c.abbrs.map((a) => abbrIdx.get(a)!.toString(36)).join(',')).join('|');

  const what = `Fully-resolved ${t.year} schedule: per class of output-identical zones, the
// abbr segments with start instants in 15-min steps since YEAR_START (baked
// offsets live in offsets.ts). Impl 07/09 serve responses from this.
// ${t.stats.zones} zones -> ${t.stats.schedClasses} schedule classes, ${t.stats.totalSegs} segments, ${abbrDict.length} distinct abbrs`;

  return `${genHeader(meta, what)}
import { decodeSchedule } from '../../decode.ts';

export type { ScheduleClass } from '../../decode.ts';

${metaExport(meta)}
export const YEAR_START = ${t.yearStart}; // Date.UTC(${t.year}, 0, 1)
export const STEP_MS = ${t.stepMs};

const P = '${codec.prefixesPacked}';
const Z = '${zonesPacked}';
const S = '${startsPacked}';
const D = '${abbrDict.join(';')}';
const A = '${abbrsPacked}';

export const scheduleClasses = decodeSchedule(P, Z, S, D, A);
`;
}

export function emitOffsetsTs(t: GeneratedTables, meta: GenMeta): string {
  // "+05:30" -> 330; formatOffsetMinutes reverses this at decode
  const toMin = (o: string) => {
    const sign = o[0] === '-' ? -1 : 1;
    return sign * (+o.slice(1, 3) * 60 + +o.slice(4, 6));
  };

  const offsetsPacked = t.scheduleClasses.map((c) => c.offsets.map(toMin).join(',')).join('|');

  const what = `Baked offsets per [class][segment], parallel to schedule.ts's
// scheduleClasses. Separate file so live-offset consumers (impl 09) don't
// bundle it; used by impl 07.`;

  return `${genHeader(meta, what)}
import { decodeOffsets } from '../../decode.ts';

${metaExport(meta)}
const O = '${offsetsPacked}';

export const scheduleOffsets: string[][] = decodeOffsets(O);
`;
}
