// Renders generated tables into shared/tables/<variant>/{classes,schedule}.ts
// source text, in the packed format decoded by shared/decode.ts. Shared by
// the bun path (tools/gen-classes.ts) and the Chrome path (tools/gen-chrome.ts)
// so both emit byte-comparable files.
//
// Packing (minified-bundle-size motivated; see shared/decode.ts):
// - zone names: prefix dictionary ("America/Argentina/" etc.), each zone
//   encoded as one base36 prefix-index char + leaf
// - classes/lists: single delimited strings instead of array literals
// - schedule classes: three packed groups by kind — static states,
//   two-state nth-weekday rules (year-independent), and current-year
//   irregular segments; offsets as signed minutes throughout

import type { GeneratedTables } from './gen-core.ts';

// provenance of the Intl data the tables were probed from; the equivalence
// tests skip when the executing runtime doesn't match
export interface GenMeta {
  host: string; // e.g. "bun 1.4.0" or "chrome-headless-shell 150.0.7871.115"
  icu: string | null; // process.versions.icu when known
  generated: string; // ISO timestamp
}

const metaExport = (meta: GenMeta) =>
  `export const genMeta = ${JSON.stringify(meta, null, 2)} as const;\n`;

const genHeader = (meta: GenMeta, what: string) =>
  `// AUTO-GENERATED by tools/gen-core.ts — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// ${what}
// generated by: ${meta.host}, ${meta.generated}
`;

interface ZoneCodec {
  prefixesPacked: string;
  encode: (zone: string) => string;
}

function zoneCodec(allZones: string[]): ZoneCodec {
  const counts = new Map<string, number>();

  for (const z of allZones) {
    const cut = z.lastIndexOf('/');
    const prefix = cut === -1 ? '' : z.slice(0, cut + 1);
    counts.set(prefix, (counts.get(prefix) ?? 0) + 1);
  }

  const prefixes = [...counts.keys()].sort((a, b) => counts.get(b)! - counts.get(a)!);

  if (prefixes.length > 36) throw new Error(`zone prefix dictionary overflow: ${prefixes.length} > 36`);

  const idx = new Map(prefixes.map((p, i) => [p, i]));

  return {
    prefixesPacked: prefixes.join('|'),
    encode: (zone) => {
      const cut = zone.lastIndexOf('/');
      const prefix = cut === -1 ? '' : zone.slice(0, cut + 1);
      return idx.get(prefix)!.toString(36) + zone.slice(cut + 1);
    },
  };
}

export function emitClassesTs(t: GeneratedTables, meta: GenMeta): string {
  const singletons = t.stats.sigClasses - t.stats.groups;
  const codec = zoneCodec(t.classGroups.flat());
  const groupsPacked = t.classGroups.map((g) => g.map(codec.encode).join(';')).join('|');

  const what = `Zones within a group have identical (CLDR long name, UTC offset) behavior
// at every instant of ${t.year} (15-min transition resolution). The first
// member of each group is the representative whose formatter serves all.
// ${t.stats.zones} zones -> ${t.stats.sigClasses} classes (${t.stats.groups} groups covering ${t.stats.grouped} zones + ${singletons} singletons)`;

  return `${genHeader(meta, what)}
import { decodeGroups } from '../../decode.ts';

${metaExport(meta)}
const P = '${codec.prefixesPacked}';
const G = '${groupsPacked}';

export const classGroups: string[][] = decodeGroups(P, G);
`;
}

export function emitScheduleTs(t: GeneratedTables, meta: GenMeta): string {
  const codec = zoneCodec(t.scheduleClasses.flatMap((c) => c.zones));

  const statics: string[] = [];
  const rules: string[] = [];
  const irregulars: string[] = [];

  for (const c of t.scheduleClasses) {
    const zs = c.zones.map(codec.encode).join(';');

    if (c.kind === 0) {
      statics.push(`${zs}~${c.states[0].abbr}~${c.states[0].offMin}`);
    } else if (c.kind === 1) {
      const st = c.states.map((s) => `${s.abbr},${s.offMin}`).join('~');
      const rs = c.rules.map((r) => `${r.month},${r.nth},${r.dow},${r.atMin},${r.to}`).join('~');
      rules.push(`${zs}~${st}~${rs}`);
    } else {
      irregulars.push(`${zs}~${c.starts.join(',')}~${c.abbrs.join(',')}~${c.offMins.join(',')}`);
    }
  }

  const what = `Year-independent schedule fitted from probing ${t.years.join('/')}: static
// states, two-state nth-weekday rules, and current-year irregular segments.
// ${t.stats.zones} zones -> ${t.stats.schedClasses} classes (${t.stats.staticClasses} static, ${t.stats.ruleClasses} rule, ${t.stats.irregularClasses} irregular covering ${t.stats.irregularZones} zones)
// Impls 07/09 serve responses from this via shared/rules.ts.`;

  return `${genHeader(meta, what)}
import { decodeSchedule } from '../../decode.ts';

export type { ScheduleClass } from '../../rules.ts';

${metaExport(meta)}
export const YEAR_START = ${t.yearStart}; // Date.UTC(${t.year}, 0, 1); anchors irregular segments
export const STEP_MS = ${t.stepMs};

const P = '${codec.prefixesPacked}';
const S = '${statics.join('|')}';
const R = '${rules.join('|')}';
const I = '${irregulars.join('|')}';

export const scheduleClasses = decodeSchedule(P, S, R, I);
`;
}
