// Renders generated tables into shared/tables/<variant>/{classes,schedule}.ts
// source text, in the packed format decoded by shared/decode.ts. Shared by
// the bun path (tools/gen-classes.ts) and the Chrome path (tools/gen-chrome.ts)
// so both emit byte-comparable files.
//
// Packing (minified-bundle-size motivated; see shared/decode.ts):
// - zone names: prefix dictionary ("America/Argentina/" etc.), each zone
//   encoded as one base36 prefix-index char + leaf
// - classes/lists: single delimited strings instead of array literals
// - schedule classes: three packed groups by kind — static states,
//   two-state nth-weekday rules (year-independent), and current-year
//   irregular segments; offsets as signed minutes throughout

import type { GeneratedTables, GeneratedHistory } from './gen-core.ts';
import type { AbbrFixResult } from './abbrfix-core.ts';
import type { HistoryEra, Rule } from '../shared/rules.ts';
import { formatOffset } from '../shared/fmt.ts';
import { ABBRFIX_OFF_BIAS } from '../shared/decode.ts';
import { zoneLinks } from '../shared/zoneLinks.ts';

// provenance of the Intl data the tables were probed from; the equivalence
// tests skip when the executing runtime doesn't match
export interface GenMeta {
  host: string; // e.g. "bun 1.4.0" or "chrome-headless-shell 150.0.7871.115"
  icu: string | null; // process.versions.icu when known
  generated: string; // ISO timestamp
}

const metaExport = (meta: GenMeta) =>
  `export const genMeta = ${JSON.stringify(meta, null, 2)} as const;\n`;

const genHeader = (meta: GenMeta, what: string, by = 'tools/gen-core.ts') =>
  `// AUTO-GENERATED by ${by} — do not edit by hand (packed data;
// see shared/decode.ts). Regenerate (bun run gen) when tzdata/CLDR changes
// or (for irregular zones) the year rolls over.
//
// ${what}
// generated by: ${meta.host}, ${meta.generated}
`;

interface ZoneCodec {
  prefixesPacked: string;
  encode: (zone: string) => string;
}

function zoneCodec(allZones: string[]): ZoneCodec {
  const counts = new Map<string, number>();

  for (const z of allZones) {
    const cut = z.lastIndexOf('/');
    const prefix = cut === -1 ? '' : z.slice(0, cut + 1);
    counts.set(prefix, (counts.get(prefix) ?? 0) + 1);
  }

  const prefixes = [...counts.keys()].sort((a, b) => counts.get(b)! - counts.get(a)!);

  if (prefixes.length > 36) throw new Error(`zone prefix dictionary overflow: ${prefixes.length} > 36`);

  const idx = new Map(prefixes.map((p, i) => [p, i]));

  return {
    prefixesPacked: prefixes.join('|'),
    encode: (zone) => {
      const cut = zone.lastIndexOf('/');
      const prefix = cut === -1 ? '' : zone.slice(0, cut + 1);
      return idx.get(prefix)!.toString(36) + zone.slice(cut + 1);
    },
  };
}

export function emitClassesTs(t: GeneratedTables, meta: GenMeta): string {
  const singletons = t.stats.sigClasses - t.stats.groups;
  const codec = zoneCodec(t.classGroups.flat());
  const groupsPacked = t.classGroups.map((g) => g.map(codec.encode).join(';')).join('|');

  const what = `Zones within a group have identical (CLDR long name, UTC offset) behavior
// at every instant of ${t.year} (15-min transition resolution). The first
// member of each group is the representative whose formatter serves all.
// ${t.stats.zones} zones -> ${t.stats.sigClasses} classes (${t.stats.groups} groups covering ${t.stats.grouped} zones + ${singletons} singletons)`;

  return `${genHeader(meta, what)}
import { decodeGroups } from '../../decode.ts';

${metaExport(meta)}
const P = '${codec.prefixesPacked}';
const G = '${groupsPacked}';

export const classGroups: string[][] = decodeGroups(P, G);
`;
}

export function emitScheduleTs(t: GeneratedTables, meta: GenMeta): string {
  const codec = zoneCodec(t.scheduleClasses.flatMap((c) => c.zones));

  const statics: string[] = [];
  const rules: string[] = [];
  const irregulars: string[] = [];

  for (const c of t.scheduleClasses) {
    const zs = c.zones.map(codec.encode).join(';');

    if (c.kind === 0) {
      statics.push(`${zs}~${c.states[0].abbr}~${c.states[0].offMin}`);
    } else if (c.kind === 1) {
      const st = c.states.map((s) => `${s.abbr},${s.offMin}`).join('~');
      const rs = c.rules.map((r) => `${r.month},${r.nth},${r.dow},${r.atMin},${r.to}`).join('~');
      rules.push(`${zs}~${st}~${rs}`);
    } else {
      irregulars.push(`${zs}~${c.starts.join(',')}~${c.abbrs.join(',')}~${c.offMins.join(',')}`);
    }
  }

  const what = `Year-independent schedule fitted from probing ${t.years.join('/')}: static
// states, two-state nth-weekday rules, and current-year irregular segments.
// ${t.stats.zones} zones -> ${t.stats.schedClasses} classes (${t.stats.staticClasses} static, ${t.stats.ruleClasses} rule, ${t.stats.irregularClasses} irregular covering ${t.stats.irregularZones} zones)
// Impls 07/09 serve responses from this via shared/rules.ts.`;

  return `${genHeader(meta, what)}
import { decodeSchedule } from '../../decode.ts';

export type { ScheduleClass } from '../../rules.ts';

${metaExport(meta)}
export const YEAR_START = ${t.yearStart}; // Date.UTC(${t.year}, 0, 1); anchors irregular segments
export const STEP_MS = ${t.stepMs};

const P = '${codec.prefixesPacked}';
const S = '${statics.join('|')}';
const R = '${rules.join('|')}';
const I = '${irregulars.join('|')}';

export const scheduleClasses = decodeSchedule(P, S, R, I);
`;
}

// ORDERING CONTRACT: the sidecar tables (history, abbrfix) address zones by
// index into the schedule table's DECODED enumeration. decodeSchedule returns
// statics, then rules, then irregulars (each preserving generator order), which
// is NOT the order scheduleClasses arrives in here, so it can't be read off the
// live array — `t.scheduleClasses.flatMap((c) => c.zones)` disagrees with the
// runtime in ~90% of positions. Every sidecar emitter must index through this.
export function scheduleZoneOrder(t: GeneratedTables): string[] {
  return [0, 1, 2].flatMap((k) => t.scheduleClasses.filter((c) => c.kind === k)).flatMap((c) => c.zones);
}

// base-36, zero-padded to a fixed field width. Width 1 is plain toString(36),
// since padStart only ever pads.
const b36 = (n: number, width = 1): string => n.toString(36).padStart(width, '0');

// zone -> index in the schedule table's enumeration, which is the index space
// every sidecar table references (see the ORDERING CONTRACT above). 1296 is the
// ceiling of a 2-char base-36 reference.
function zoneIndex(t: GeneratedTables): Map<string, number> {
  const ordered = scheduleZoneOrder(t);

  if (ordered.length > 1296) throw new Error(`zone index overflow: ${ordered.length} > 1296`);

  return new Map(ordered.map((z, i) => [z, i]));
}

// A shared dictionary: hands each distinct payload a stable index in first-use
// order and returns a fixed-width base-36 reference to it. All the packing wins
// come from one of these — a few dozen distinct payloads back hundreds of
// references, so the references are what the table actually spends bytes on.
function interner(width: number) {
  const values: string[] = [];
  const idx = new Map<string, number>();

  return {
    values,
    // `key` identifies the entry; pass `stored` when the shipped form differs
    // from the identity (rule tuples pack their fields, and key on the raw ones)
    ref(key: string, stored: string = key): string {
      let i = idx.get(key);

      if (i == null) {
        i = values.length;
        values.push(stored);
        idx.set(key, i);
      }

      return b36(i, width);
    },
  };
}

export function emitHistoryTs(h: GeneratedHistory, t: GeneratedTables, meta: GenMeta): string {
  const zoneIdx = zoneIndex(t);

  const eraDict = interner(2);
  const pairDict = interner(2);
  const tupleDict = interner(2);

  // OFFSETS ship in quarter-hour units — every real UTC offset is a multiple of
  // 15 min, including the :45 ones (Kathmandu +05:45, Chatham +12:45). Rule wall
  // times are NOT: see tupleRef.
  const q = (min: number): number => {
    if (min % 15 !== 0) throw new Error(`sub-quarter-hour offset in history: ${min}`);
    return min / 15;
  };

  // rule-span offset pairs get their own dictionary: only ~38 distinct pairs
  // back hundreds of rule spans, so a 2-char index beats inlining 'qA,qB'
  const pairRef = (offA: number, offB: number): string => pairDict.ref(`${q(offA)},${q(offB)}`);

  // rule (month, nth, dow, at) tuples get their own dictionary too, as fixed
  // 6-char records (no delimiters): the same tuple recurs across many offset
  // pairs (the US and EU shapes especially). at is WALL MINUTES (0..1439) in 3
  // chars, not quarter-hours: Atlantic Canada switched at 00:01 local until
  // 2011 and Antarctica/Casey in 2020-22, so rounding here would put the
  // transition 14 minutes late. Only the ~200 dictionary records pay the extra
  // char; the 2-char references that actually recur are unchanged.
  const tupleRef = (r: Rule): string => {
    if (r.atMin < 0 || r.atMin > 1439) throw new Error(`rule wall minute out of range: ${r.atMin}`);

    return tupleDict.ref(
      `${r.month},${r.nth},${r.dow},${r.atMin}`,
      `${b36(r.month)}${b36(r.nth)}${b36(r.dow)}${b36(r.atMin, 3)}`
    );
  };

  const eraPayload = (e: HistoryEra): string => {
    if (e.kind === 3) return 'd'; // defer to the schedule class

    if (e.kind === 0) return `s${q(e.offs[0]!)}`;

    if (e.kind === 1) {
      // to flags implicit: rule 1 -> offs[1], rule 2 -> offs[0]
      return `r${pairRef(e.offs[0]!, e.offs[1]!)}${tupleRef(e.rules![0])}${tupleRef(e.rules![1])}`;
    }

    return `w${e.steps!.map((s, i) => `${b36(s, 3)}${q(e.offs[i]!)}`).join(',')}`;
  };

  const classes = h.classes.map((c) => {
    const zs = c.zones.map((z) => b36(zoneIdx.get(z)!, 2)).join('');

    const eras = c.eras
      .map((e) => `${b36(e.fromYear - h.fromYear)}${eraDict.ref(eraPayload(e))}`)
      .join('');

    return `${zs}~${eras}`;
  });

  const dict = eraDict.values;
  const pairs = pairDict.values;
  const tuples = tupleDict.values;

  if (dict.length > 1296) throw new Error(`era dictionary overflow: ${dict.length} > 1296`);
  if (pairs.length > 1296) throw new Error(`offset-pair dictionary overflow: ${pairs.length} > 1296`);
  if (tuples.length > 1296) throw new Error(`rule tuple dictionary overflow: ${tuples.length} > 1296`);
  // fixed 6-char tuple records assume single-char month/nth/dow and 3-char at
  if (tuples.some((rec) => rec.length !== 6)) throw new Error('rule tuple field out of single-char range');

  const s = h.stats;
  const what = `Historical offset eras (${h.fromYear}-${h.toYear - 1}; the main schedule covers ${h.toYear}+):
// static spans, two-rule DST spans, raw single years, and defer spans
// (schedule class already exact — nothing stored). Offsets only — no
// abbreviations. Irregular-class zones are excluded; fully schedule-covered
// zones (${s.coveredZones}) have no entry at all. Zones reference the schedule
// table's zone enumeration by index; era payloads are dictionary-shared.
// ${s.zones} zones -> ${s.classes} classes (${s.staticEras} static, ${s.ruleEras} rule, ${s.rawYears} raw, ${s.deferEras} defer eras; ${dict.length} distinct payloads, ${pairs.length} offset pairs, ${tuples.length} rule tuples)
// Consumed via shared/rules.ts resolveHistory (tools/sweep-validity.ts validates).`;

  return `${genHeader(meta, what)}
import { decodeHistory } from '../../decode.ts';
import { scheduleClasses } from './schedule.ts';

${metaExport(meta)}
export const HISTORY_FROM = ${h.fromYear};
export const HISTORY_TO = ${h.toYear}; // exclusive; the bake year

// see emitHistoryTs: this flatten order is the zone-index space. The eager
// decode is /*@__PURE__*/ so bundlers drop this whole table when nothing
// references historyClasses (schedule-only entry points like getTimeZones()).
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const P = '${pairs.join('|')}';
const T = '${tuples.join('')}';
const E = '${dict.join('|')}';
const H = '${classes.join('|')}';

export const historyClasses = /*@__PURE__*/ decodeHistory(Z, P, T, E, H, HISTORY_FROM);
`;
}

// Historical abbreviation corrections (shared/tables/<variant>/abbrfix.ts):
// the spans where the offset-keyed historical label disagrees with live Intl.
// See tools/abbrfix-core.ts for how they're found and shared/rules.ts
// AbbrFixClass for what they mean. Takes the whole table set rather than a zone
// list so the index space comes from scheduleZoneOrder and cannot be passed in
// wrong — see the ORDERING CONTRACT above.
export function emitAbbrFixTs(
  result: AbbrFixResult,
  t: GeneratedTables,
  fromYear: number,
  toYear: number,
  meta: GenMeta
): string {
  const zoneIdx = zoneIndex(t);
  const abbrDict = interner(1);
  const dict = abbrDict.values;
  const abbrRef = (abbr: string): string => abbrDict.ref(abbr);

  const classes: string[] = [];

  for (const c of result.classes) {
    // The audit walks the RUNTIME zone list, which includes tzdata link
    // spellings (America/Buenos_Aires) that the index space — the generating
    // runtime's own enumeration — may not carry. Bridge them exactly as
    // buildScheduleIndex does at runtime, and drop anything still unaddressable:
    // it resolves to -1 there anyway.
    const idxs = [
      ...new Set(
        c.zones
          .map((z) => zoneIdx.get(z) ?? zoneIdx.get(zoneLinks.get(z) ?? ''))
          .filter((i): i is number => i != null)
      ),
    ].sort((a, b) => a - b);

    if (idxs.length === 0) continue;

    const zs = idxs.map((i) => i.toString(36).padStart(2, '0')).join('');

    // years are relative to fromYear (one base-36 digit for a 31-year span) and
    // offsets are biased quarter-hours (one or two)
    const ranges = c.ranges
      .map((r) => {
        if (r.offMin % 15 !== 0) throw new Error(`abbrfix offset not a quarter hour: ${r.offMin}`);

        return `${b36(r.fromYear - fromYear)},${b36(r.toYear - r.fromYear)},${b36(r.offMin / 15 + ABBRFIX_OFF_BIAS)},${abbrRef(r.abbr)}`;
      })
      .join(';');

    // delta-coded off the previous span's END, so both fields stay short
    let cursor = 0;
    const spans = c.spans
      .map((s) => {
        const gap = s.from - cursor;

        if (gap < 0) throw new Error(`abbrfix spans out of order for ${c.zones[0]}`);

        cursor = s.to;

        return `${b36(gap)},${b36(s.to - s.from)},${abbrRef(s.abbr)}`;
      })
      .join(';');

    classes.push(`${zs}~${ranges}~${spans}`);
  }

  if (dict.some((a) => /[,;|~]/.test(a))) throw new Error('abbreviation contains a delimiter');

  const s = result.stats;
  const what = `Historical abbreviation corrections (${fromYear}-${toYear - 1}), layered over the
// offset-only history eras. history.ts stores no labels, so below the bake year
// an abbreviation is derived from the resolved OFFSET alone — which is wrong
// wherever a zone's historical identity differs from its modern schedule class
// (America/Ciudad_Juarez was Central in 1998; -360 matches its modern Mountain
// class's MDT). These carry the label live Intl reports, for the instants where
// that answer is a confident lie. Where the offset matches no modern state (so
// the fallback is a vague GMT±N rather than a wrong name) it is NOT corrected.
//
// Keyed by (year range, offset), not by timestamp: the wrong label is itself a
// function of the offset, so a record need only say "in these years this offset
// means X". ${s.spans} disagreeing spans collapse to ${s.ranges} range records; the
// ${s.fallbackSpans} spans that survive cover years where one offset holds two identities.
// ${s.zones} zones -> ${result.classes.length} shared payloads, ${dict.length} distinct labels
// (${s.deferSpans} of the spans land in defer eras, resolved via the schedule class)
// Covers ${s.lieZoneYears} zone-years that would otherwise be mislabelled.
// Consumed via shared/rules.ts resolveAbbrFix (tests/history.test.ts pins it).`;

  return `${genHeader(meta, what, 'tools/gen-abbrfix.ts')}
import { decodeAbbrFix } from '../../decode.ts';
import { scheduleClasses, STEP_MS } from './schedule.ts';

${metaExport(meta)}
export const ABBRFIX_FROM = ${fromYear};

// same zone-index space as history.ts. The eager decode is /*@__PURE__*/ so a
// bundler drops this table whenever nothing references abbrFixClasses — which
// is every schedule-only entry point, since only shared/bakedHistory.ts reads it.
const Z = /*@__PURE__*/ scheduleClasses.flatMap((c) => c.zones);
const A = '${dict.join(',')}';
const F = '${classes.join('|')}';

export const abbrFixClasses = /*@__PURE__*/ decodeAbbrFix(Z, A, F, ABBRFIX_FROM, STEP_MS);
`;
}

// Pre-baked signed-offset-minutes -> "±HH:MM" lookup. `offsets` is the sorted
// set of distinct offsets observed across the schedule + history tables (see
// tools/gen-offsets.ts); the public formatOffset() reads this and only formats
// on the fly for offsets outside the baked set (arbitrary caller input, or a
// live Intl/Temporal offset no baked table covers).
export function emitOffsetsTs(offsets: number[], meta: GenMeta): string {
  const entries = offsets.map((o) => `  [${o}, '${formatOffset(o)}'],`).join('\n');

  const what = `Pre-baked signed-offset-minutes -> "±HH:MM" string lookup: the ${offsets.length}
// distinct UTC offsets across the schedule + history tables. formatOffset()
// resolves these with a Map.get and formats on the fly only outside this set.`;

  return `${genHeader(meta, what)}
export const offsetStrings: ReadonlyMap<number, string> = new Map([
${entries}
]);
`;
}
